In [4]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score
from scipy.stats import ks_2samp
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv('model_validation.csv', sep=';')

In [6]:
df.head()

,CC_ID,SCORING_ID,LOAN_ID,SCORE_BALL,APPLICATION_DATE,TARGET_30,TARGET_60,TARGET_90
0,1463,42,1107792,38,19.07.2022,0.0,0.0,0.0
1,1467,42,1107613,38,19.07.2022,0.0,0.0,0.0
2,1520,42,1108049,40,20.07.2022,0.0,0.0,0.0
3,1539,42,1108413,45,21.07.2022,1.0,0.0,0.0
4,1604,42,1110647,41,25.07.2022,0.0,0.0,0.0

In [7]:
df.shape

(80397, 8)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80397 entries, 0 to 80396
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CC_ID             80397 non-null  int64
 1   SCORING_ID        80397 non-null  int64
 2   LOAN_ID           80397 non-null  int64
 3   SCORE_BALL        80397 non-null  int64
 4   APPLICATION_DATE  80397 non-null  object
 5   TARGET_30         77452 non-null  float64
 6   TARGET_60         77452 non-null  float64
 7   TARGET_90         77452 non-null  float64
dtypes: float64(3), int64(4), object(1)
memory usage: 4.9+ MB

In [9]:
df[(df['TARGET_90'].isnull()) & (df['SCORING_ID'] == 727)].head(15)

,CC_ID,SCORING_ID,LOAN_ID,SCORE_BALL,APPLICATION_DATE,TARGET_30,TARGET_60,TARGET_90
47222,780847,727,1528162,870,24.02.2025,NaN,NaN,NaN
47598,782382,727,1528337,870,25.02.2025,NaN,NaN,NaN
47765,783048,727,1528626,850,26.02.2025,NaN,NaN,NaN
47792,783188,727,1528850,870,26.02.2025,NaN,NaN,NaN
47947,783828,727,1529190,760,27.02.2025,NaN,NaN,NaN
48059,784157,727,1529240,870,27.02.2025,NaN,NaN,NaN
48218,784685,727,1529454,870,27.02.2025,NaN,NaN,NaN
48240,784770,727,1529512,750,27.02.2025,NaN,NaN,NaN
48252,784800,727,1529533,750,27.02.2025,NaN,NaN,NaN
48270,784897,727,1529606,870,27.02.2025,NaN,NaN,NaN
48419,785546,727,1529881,760,28.02.2025,NaN,NaN,NaN
48629,786598,727,1530493,820,03.03.2025,NaN,NaN,NaN
50340,792151,727,1532750,760,06.03.2025,NaN,NaN,NaN
51125,795115,727,1534025,750,11.03.2025,NaN,NaN,NaN
52097,798947,727,1535391,830,13.03.2025,NaN,NaN,NaN

In [10]:
df['APPLICATION_DATE'] = pd.to_datetime(
    df['APPLICATION_DATE'],
    format='%d.%m.%Y'
)
df[df['TARGET_90'].isnull()]
df = df.dropna(subset=['TARGET_90'])

In [11]:
df.shape

(77452, 8)

In [8]:
df.groupby('SCORING_ID')['APPLICATION_DATE'].agg({min, max})

C:\Users\sh.nabiyev\AppData\Local\Temp\ipykernel_12048\985070687.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('SCORING_ID')['APPLICATION_DATE'].agg({min, max})
C:\Users\sh.nabiyev\AppData\Local\Temp\ipykernel_12048\985070687.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('SCORING_ID')['APPLICATION_DATE'].agg({min, max})

                  min        max
SCORING_ID
42         2022-07-19 2026-03-10
122        2022-10-17 2026-03-13
184        2023-01-06 2026-02-18
343        2024-02-09 2025-11-19
504        2024-06-19 2026-03-27
727        2025-01-22 2026-06-08

In [9]:
from sklearn.metrics import roc_auc_score
from scipy.stats import ks_2samp
import pandas as pd

max_date = df['APPLICATION_DATE'].max()

summary = []

df = df.copy()
df['APPLICATION_DATE'] = pd.to_datetime(df['APPLICATION_DATE'])

targets = {
    'TARGET_30': 30,
    'TARGET_60': 60,
    'TARGET_90': 90
}

for scoring_id, df_model in df.groupby('SCORING_ID'):

    for target, maturity_days in targets.items():

        # Maturity filter
        cutoff_date = max_date - pd.Timedelta(days=maturity_days)

        tmp = (
            df_model.loc[
                df_model['APPLICATION_DATE'] <= cutoff_date,
                [target, 'SCORE_BALL']
            ]
            .dropna()
        )

        if len(tmp) < 50:
            continue

        if tmp[target].nunique() < 2:
            continue

        # AUC
        auc = roc_auc_score(
            tmp[target],
            -tmp['SCORE_BALL']
        )

        # GINI
        gini = 2 * auc - 1

        # KS
        good_scores = tmp.loc[
            tmp[target] == 0,
            'SCORE_BALL'
        ]

        bad_scores = tmp.loc[
            tmp[target] == 1,
            'SCORE_BALL'
        ]

        ks = ks_2samp(
            -good_scores,
            -bad_scores
        ).statistic

        summary.append({
            'SCORING_ID': scoring_id,
            'TARGET': target,
            'OBS': len(tmp),
            'BAD_RATE': round(tmp[target].mean() * 100, 2),
            'AUC': round(auc, 4),
            'GINI': round(gini, 4),
            'KS': round(ks, 4),
            'START_DATE': df_model['APPLICATION_DATE'].min().date(),
            'END_DATE': cutoff_date.date()
        })

summary_df = (
    pd.DataFrame(summary)
    .sort_values(['SCORING_ID', 'TARGET'])
    .reset_index(drop=True)
)

summary_df

,SCORING_ID,TARGET,OBS,BAD_RATE,AUC,GINI,KS,START_DATE,END_DATE
0,42,TARGET_30,2643,21.11,0.5459,0.0919,0.0776,2022-07-19,2026-05-09
1,42,TARGET_60,2643,6.92,0.5651,0.1303,0.1086,2022-07-19,2026-04-09
2,42,TARGET_90,2643,4.01,0.5420,0.0839,0.0783,2022-07-19,2026-03-10
3,122,TARGET_30,1272,30.82,0.5336,0.0672,0.1221,2022-10-17,2026-05-09
4,122,TARGET_60,1272,12.89,0.5398,0.0795,0.1599,2022-10-17,2026-04-09
5,122,TARGET_90,1271,8.18,0.5384,0.0768,0.1488,2022-10-17,2026-03-10
6,184,TARGET_30,6731,31.61,0.5679,0.1358,0.1171,2023-01-06,2026-05-09
7,184,TARGET_60,6731,15.72,0.5640,0.1279,0.1025,2023-01-06,2026-04-09
8,184,TARGET_90,6731,10.41,0.5639,0.1278,0.0969,2023-01-06,2026-03-10
9,343,TARGET_30,46728,68.95,0.5170,0.0340,0.0321,2024-02-09,2026-05-09
10,343,TARGET_60,46728,48.10,0.5134,0.0267,0.0263,2024-02-09,2026-04-09
11,343,TARGET_90,46728,37.82,0.5083,0.0165,0.0223,2024-02-09,2026-03-10
12,504,TARGET_30,1118,45.08,0.6045,0.2090,0.1562,2024-06-19,2026-05-09
13,504,TARGET_60,1118,32.20,0.6211,0.2423,0.1795,2024-06-19,2026-04-09
14,504,TARGET_90,1116,26.43,0.6151,0.2301,0.1652,2024-06-19,2026-03-10
15,727,TARGET_30,18827,7.25,0.7202,0.4404,0.3342,2025-01-22,2026-05-09
16,727,TARGET_60,18663,2.13,0.7303,0.4605,0.3686,2025-01-22,2026-04-09
17,727,TARGET_90,18505,1.15,0.7283,0.4566,0.3738,2025-01-22,2026-03-10

In [1]:
# SCORING_ID = 42
# Portfelning BAD RATE ko‘rsatkichlari TARGET_30 bo‘yicha 21.1%, TARGET_60 bo‘yicha 6.9% va TARGET_90 bo‘yicha 4.0% ni tashkil etadi. 
# Modelning AUC (0.54–0.57), GINI (0.08–0.13) va KS (0.08–0.11) qiymatlari past bo‘lib, modelning risk segmentlarini ajratish qobiliyati 
# cheklanganligini ko‘rsatadi.
# 
# SCORING_ID = 122
# BAD RATE darajasi TARGET_30 bo‘yicha 30.8% ga yetadi. AUC (0.53–0.54), GINI (0.07–0.08) va KS (0.12–0.16) qiymatlari modelning ajratuvchanlik
# darajasi past ekanligini ko‘rsatmoqda. 
# 
# SCORING_ID = 184
# Portfelning default darajasi nisbatan yuqori (TARGET_30 = 31.6%). AUC (0.56–0.57), GINI (0.13 atrofida) va KS (0.10–0.12) qiymatlari 
# modelning ma'lum darajada ajratuvchanlikka ega ekanligini ko‘rsatsa-da, natijalar kuchli diskriminatsion qobiliyat mavjudligini tasdiqlamaydi.
# 
# SCORING_ID = 343
# Portfel BAD RATE ko‘rsatkichlari juda yuqori (TARGET_30 = 69.0%, TARGET_60 = 48.1%, TARGET_90 = 37.8%). Shu bilan birga AUC (0.51–0.52), 
# GINI (0.02–0.03) va KS (0.02–0.03) qiymatlari juda past bo‘lib, model ballari va kuzatilgan risk darajasi o‘rtasidagi bog‘liqlik zaif 
# ekanligini ko‘rsatadi.
# 
# SCORING_ID = 504
# Portfelda BAD RATE yuqori bo‘lishiga qaramay (TARGET_30 = 45.1%), modelning AUC (0.60–0.62), GINI (0.21–0.24) va KS (0.16–0.18) ko‘rsatkichlari
# boshqa ayrim modellarga nisbatan yaxshiroq natijalarni namoyish etmoqda. Biroq ko‘rsatkichlar modelni yuqori sifatli deb baholash uchun 
# yetarli darajada emas.
# 
# SCORING_ID = 727
# Portfelning BAD RATE darajasi boshqa modellarga nisbatan ancha past (TARGET_30 = 7.3%, TARGET_60 = 2.1%, TARGET_90 = 1.2%). 
# AUC (0.72–0.73), GINI (0.44–0.46) va KS (0.33–0.37) qiymatlari model ballari bilan kuzatilgan risk o‘rtasida nisbatan kuchli bog‘liqlik 
# mavjudligini ko‘rsatadi. Tahlil qilingan modellar orasida ushbu model eng yaxshi diskriminatsion ko‘rsatkichlarni namoyish etgan.

In [10]:
df.groupby('SCORING_ID').agg(
    cnt=('SCORING_ID', 'count'),
    dr30=('TARGET_30', 'mean'),
    dr60=('TARGET_60', 'mean'),
    dr90=('TARGET_90', 'mean')
).reset_index()

   SCORING_ID    cnt      dr30      dr60      dr90
0          42   2643  0.211124  0.069240  0.040106
1         122   1272  0.308176  0.128931  0.081761
2         184   6731  0.316149  0.157183  0.104145
3         343  46728  0.689522  0.480954  0.378167
4         504   1118  0.450805  0.322004  0.263864
5         727  18960  0.071994  0.020939  0.011181

In [11]:
def make_decile(df_model, target, cutoff_date):

    tmp = df_model.loc[
        df_model['APPLICATION_DATE'] <= cutoff_date,
        [target, 'SCORE_BALL']
    ].dropna().copy()

    if len(tmp) < 100 or tmp[target].nunique() < 2:
        return None

    # =========================
    # DECILE (HIGH SCORE = LOW RISK assumption kept consistent)
    # =========================
    tmp['DECILE'] = pd.qcut(
        tmp['SCORE_BALL'],
        q=10,
        labels=False,
        duplicates='drop'
    ) + 1

    report = (
        tmp.groupby('DECILE')
        .agg(
            cnt=(target, 'count'),
            bads=(target, 'sum'),
            bad_rate=(target, 'mean'),
            min_score=('SCORE_BALL', 'min'),
            max_score=('SCORE_BALL', 'max')
        )
        .reset_index()
        .sort_values('DECILE')
    )

    report['bad_rate'] = (report['bad_rate'] * 100).round(2)

    report['cum_cnt'] = report['cnt'].cumsum()
    report['cum_bads'] = report['bads'].cumsum()

    return report

max_date = df['APPLICATION_DATE'].max()

targets = {
    'TARGET_30': 30,
    'TARGET_60': 60,
    'TARGET_90': 90
}

all_reports = {}

for scoring_id, df_model in df.groupby('SCORING_ID'):

    print("\n" + "=" * 100)
    print(f"MODEL: {scoring_id}")
    print("=" * 100)

    for target, maturity_days in targets.items():

        cutoff_date = max_date - pd.Timedelta(days=maturity_days)

        report = make_decile(df_model, target, cutoff_date)

        if report is None:
            print(f"\n{target}: insufficient data")
            continue

        all_reports[(scoring_id, target)] = report

        print("\n" + "-" * 100)
        print(f"MODEL = {scoring_id} | TARGET = {target}")
        print(f"PERIOD <= {cutoff_date.date()}")
        print("-" * 100)

        print(report)

        # =========================
        # MONOTONICITY CHECK (FIXED LOGIC)
        # =========================
        monotonic = report['bad_rate'].is_monotonic_decreasing
        violations = (report['bad_rate'].diff() > 0).sum()

        print(f"\nMonotonicity: {'PASS' if monotonic else 'FAIL'}")
        print(f"Violations: {violations}")

        print(
            f"Bad Rate Range: "
            f"{report['bad_rate'].max():.2f}% -> {report['bad_rate'].min():.2f}%"
        )

====================================================================================================
MODEL: 42
====================================================================================================

----------------------------------------------------------------------------------------------------
MODEL = 42 | TARGET = TARGET_30
PERIOD <= 2026-05-09
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  272  81.0     29.78       -150         34      272      81.0
1       2  350  73.0     20.86         35         38      622     154.0
2       3  211  52.0     24.64         39         40      833     206.0
3       4  282  60.0     21.28         41         42     1115     266.0
4       5  233  41.0     17.60         43         44     1348     307.0
5       6  269  47.0     17.47         45         48     1617     354.0
6       7  253  56.0     22.13         49         60     1870     410.0
7       8  280  66.0     23.57         61         67     2150     476.0
8       9  254  52.0     20.47         68         72     2404     528.0
9      10  239  30.0     12.55         73         89     2643     558.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 29.78% -> 12.55%

----------------------------------------------------------------------------------------------------
MODEL = 42 | TARGET = TARGET_60
PERIOD <= 2026-04-09
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  272  31.0     11.40       -150         34      272      31.0
1       2  350  27.0      7.71         35         38      622      58.0
2       3  211  18.0      8.53         39         40      833      76.0
3       4  282  16.0      5.67         41         42     1115      92.0
4       5  233  14.0      6.01         43         44     1348     106.0
5       6  269  15.0      5.58         45         48     1617     121.0
6       7  253  14.0      5.53         49         60     1870     135.0
7       8  280  23.0      8.21         61         67     2150     158.0
8       9  254  20.0      7.87         68         72     2404     178.0
9      10  239   5.0      2.09         73         89     2643     183.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 11.40% -> 2.09%

----------------------------------------------------------------------------------------------------
MODEL = 42 | TARGET = TARGET_90
PERIOD <= 2026-03-10
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  272  18.0      6.62       -150         34      272      18.0
1       2  350  10.0      2.86         35         38      622      28.0
2       3  211  11.0      5.21         39         40      833      39.0
3       4  282  11.0      3.90         41         42     1115      50.0
4       5  233   8.0      3.43         43         44     1348      58.0
5       6  269  12.0      4.46         45         48     1617      70.0
6       7  253   7.0      2.77         49         60     1870      77.0
7       8  280  12.0      4.29         61         67     2150      89.0
8       9  254  14.0      5.51         68         72     2404     103.0
9      10  239   3.0      1.26         73         89     2643     106.0

Monotonicity: FAIL
Violations: 4
Bad Rate Range: 6.62% -> 1.26%

====================================================================================================
MODEL: 122
====================================================================================================

----------------------------------------------------------------------------------------------------
MODEL = 122 | TARGET = TARGET_30
PERIOD <= 2026-05-09
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  142  37.0     26.06       -151         45      142      37.0
1       2  126  39.0     30.95         46         50      268      76.0
2       3  122  45.0     36.89         51         57      390     121.0
3       4  165  57.0     34.55         58         60      555     178.0
4       5   96  29.0     30.21         61         62      651     207.0
5       6  128  53.0     41.41         63         64      779     260.0
6       7  137  46.0     33.58         65         66      916     306.0
7       8  109  43.0     39.45         67         68     1025     349.0
8       9  142  27.0     19.01         69         72     1167     376.0
9      10  105  16.0     15.24         73         84     1272     392.0

Monotonicity: FAIL
Violations: 4
Bad Rate Range: 41.41% -> 15.24%

----------------------------------------------------------------------------------------------------
MODEL = 122 | TARGET = TARGET_60
PERIOD <= 2026-04-09
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  142  14.0      9.86       -151         45      142      14.0
1       2  126  14.0     11.11         46         50      268      28.0
2       3  122  20.0     16.39         51         57      390      48.0
3       4  165  27.0     16.36         58         60      555      75.0
4       5   96  14.0     14.58         61         62      651      89.0
5       6  128  23.0     17.97         63         64      779     112.0
6       7  137  20.0     14.60         65         66      916     132.0
7       8  109  23.0     21.10         67         68     1025     155.0
8       9  142   8.0      5.63         69         72     1167     163.0
9      10  105   1.0      0.95         73         84     1272     164.0

Monotonicity: FAIL
Violations: 4
Bad Rate Range: 21.10% -> 0.95%

----------------------------------------------------------------------------------------------------
MODEL = 122 | TARGET = TARGET_90
PERIOD <= 2026-03-10
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  142   6.0      4.23       -151         45      142       6.0
1       2  126  11.0      8.73         46         50      268      17.0
2       3  121  12.0      9.92         51         57      389      29.0
3       4  165  21.0     12.73         58         60      554      50.0
4       5   96   8.0      8.33         61         62      650      58.0
5       6  128  13.0     10.16         63         64      778      71.0
6       7  137  15.0     10.95         65         66      915      86.0
7       8  109  12.0     11.01         67         68     1024      98.0
8       9  142   5.0      3.52         69         72     1166     103.0
9      10  105   1.0      0.95         73         84     1271     104.0

Monotonicity: FAIL
Violations: 6
Bad Rate Range: 12.73% -> 0.95%

====================================================================================================
MODEL: 184
====================================================================================================

----------------------------------------------------------------------------------------------------
MODEL = 184 | TARGET = TARGET_30
PERIOD <= 2026-05-09
----------------------------------------------------------------------------------------------------
   DECILE  cnt   bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  752  303.0     40.29       -155         41      752     303.0
1       2  611  231.0     37.81         42         48     1363     534.0
2       3  723  271.0     37.48         49         55     2086     805.0
3       4  628  219.0     34.87         56         59     2714    1024.0
4       5  731  200.0     27.36         60         62     3445    1224.0
5       6  784  217.0     27.68         63         65     4229    1441.0
6       7  585  187.0     31.97         66         67     4814    1628.0
7       8  813  216.0     26.57         68         70     5627    1844.0
8       9  528  165.0     31.25         71         73     6155    2009.0
9      10  576  119.0     20.66         74         88     6731    2128.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 40.29% -> 20.66%

----------------------------------------------------------------------------------------------------
MODEL = 184 | TARGET = TARGET_60
PERIOD <= 2026-04-09
----------------------------------------------------------------------------------------------------
   DECILE  cnt   bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  752  153.0     20.35       -155         41      752     153.0
1       2  611  112.0     18.33         42         48     1363     265.0
2       3  723  143.0     19.78         49         55     2086     408.0
3       4  628  105.0     16.72         56         59     2714     513.0
4       5  731  104.0     14.23         60         62     3445     617.0
5       6  784  109.0     13.90         63         65     4229     726.0
6       7  585   95.0     16.24         66         67     4814     821.0
7       8  813  109.0     13.41         68         70     5627     930.0
8       9  528   79.0     14.96         71         73     6155    1009.0
9      10  576   49.0      8.51         74         88     6731    1058.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 20.35% -> 8.51%

----------------------------------------------------------------------------------------------------
MODEL = 184 | TARGET = TARGET_90
PERIOD <= 2026-03-10
----------------------------------------------------------------------------------------------------
   DECILE  cnt   bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  752  102.0     13.56       -155         41      752     102.0
1       2  611   75.0     12.27         42         48     1363     177.0
2       3  723   95.0     13.14         49         55     2086     272.0
3       4  628   66.0     10.51         56         59     2714     338.0
4       5  731   72.0      9.85         60         62     3445     410.0
5       6  784   76.0      9.69         63         65     4229     486.0
6       7  585   66.0     11.28         66         67     4814     552.0
7       8  813   68.0      8.36         68         70     5627     620.0
8       9  528   51.0      9.66         71         73     6155     671.0
9      10  576   30.0      5.21         74         88     6731     701.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 13.56% -> 5.21%

====================================================================================================
MODEL: 343
====================================================================================================

----------------------------------------------------------------------------------------------------
MODEL = 343 | TARGET = TARGET_30
PERIOD <= 2026-05-09
----------------------------------------------------------------------------------------------------
   DECILE   cnt    bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  5272  3707.0     70.31         45         51     5272    3707.0
1       2  4107  2792.0     67.98         52         53     9379    6499.0
2       3  6107  4277.0     70.03         54         55    15486   10776.0
3       4  4172  2964.0     71.05         56         56    19658   13740.0
4       5  3784  2646.0     69.93         57         57    23442   16386.0
5       6  6002  4164.0     69.38         58         59    29444   20550.0
6       7  4034  2837.0     70.33         60         61    33478   23387.0
7       8  5736  3917.0     68.29         62         64    39214   27304.0
8       9  3012  2058.0     68.33         65         66    42226   29362.0
9      10  4502  2858.0     63.48         67         76    46728   32220.0

Monotonicity: FAIL
Violations: 4
Bad Rate Range: 71.05% -> 63.48%

----------------------------------------------------------------------------------------------------
MODEL = 343 | TARGET = TARGET_60
PERIOD <= 2026-04-09
----------------------------------------------------------------------------------------------------
   DECILE   cnt    bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  5272  2613.0     49.56         45         51     5272    2613.0
1       2  4107  1944.0     47.33         52         53     9379    4557.0
2       3  6107  3033.0     49.66         54         55    15486    7590.0
3       4  4172  2099.0     50.31         56         56    19658    9689.0
4       5  3784  1780.0     47.04         57         57    23442   11469.0
5       6  6002  2851.0     47.50         58         59    29444   14320.0
6       7  4034  2009.0     49.80         60         61    33478   16329.0
7       8  5736  2766.0     48.22         62         64    39214   19095.0
8       9  3012  1432.0     47.54         65         66    42226   20527.0
9      10  4502  1947.0     43.25         67         76    46728   22474.0

Monotonicity: FAIL
Violations: 4
Bad Rate Range: 50.31% -> 43.25%

----------------------------------------------------------------------------------------------------
MODEL = 343 | TARGET = TARGET_90
PERIOD <= 2026-03-10
----------------------------------------------------------------------------------------------------
   DECILE   cnt    bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  5272  2025.0     38.41         45         51     5272    2025.0
1       2  4107  1523.0     37.08         52         53     9379    3548.0
2       3  6107  2405.0     39.38         54         55    15486    5953.0
3       4  4172  1627.0     39.00         56         56    19658    7580.0
4       5  3784  1372.0     36.26         57         57    23442    8952.0
5       6  6002  2230.0     37.15         58         59    29444   11182.0
6       7  4034  1588.0     39.37         60         61    33478   12770.0
7       8  5736  2234.0     38.95         62         64    39214   15004.0
8       9  3012  1144.0     37.98         65         66    42226   16148.0
9      10  4502  1523.0     33.83         67         76    46728   17671.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 39.38% -> 33.83%

====================================================================================================
MODEL: 504
====================================================================================================

----------------------------------------------------------------------------------------------------
MODEL = 504 | TARGET = TARGET_30
PERIOD <= 2026-05-09
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  122  77.0     63.11         45         58      122      77.0
1       2  121  66.0     54.55         59         61      243     143.0
2       3  132  61.0     46.21         62         63      375     204.0
3       4  129  55.0     42.64         64         65      504     259.0
4       5   79  41.0     51.90         66         66      583     300.0
5       6  119  54.0     45.38         67         68      702     354.0
6       7   85  44.0     51.76         69         69      787     398.0
7       8  120  38.0     31.67         70         71      907     436.0
8       9  100  34.0     34.00         72         73     1007     470.0
9      10  111  34.0     30.63         74         86     1118     504.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 63.11% -> 30.63%

----------------------------------------------------------------------------------------------------
MODEL = 504 | TARGET = TARGET_60
PERIOD <= 2026-04-09
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  122  62.0     50.82         45         58      122      62.0
1       2  121  53.0     43.80         59         61      243     115.0
2       3  132  46.0     34.85         62         63      375     161.0
3       4  129  39.0     30.23         64         65      504     200.0
4       5   79  27.0     34.18         66         66      583     227.0
5       6  119  32.0     26.89         67         68      702     259.0
6       7   85  34.0     40.00         69         69      787     293.0
7       8  120  26.0     21.67         70         71      907     319.0
8       9  100  23.0     23.00         72         73     1007     342.0
9      10  111  18.0     16.22         74         86     1118     360.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 50.82% -> 16.22%

----------------------------------------------------------------------------------------------------
MODEL = 504 | TARGET = TARGET_90
PERIOD <= 2026-03-10
----------------------------------------------------------------------------------------------------
   DECILE  cnt  bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  122  48.0     39.34         45         58      122      48.0
1       2  120  48.0     40.00         59         61      242      96.0
2       3  132  34.0     25.76         62         63      374     130.0
3       4  128  32.0     25.00         64         65      502     162.0
4       5   79  25.0     31.65         66         66      581     187.0
5       6  119  26.0     21.85         67         68      700     213.0
6       7   85  30.0     35.29         69         69      785     243.0
7       8  120  23.0     19.17         70         71      905     266.0
8       9  100  16.0     16.00         72         73     1005     282.0
9      10  111  13.0     11.71         74         86     1116     295.0

Monotonicity: FAIL
Violations: 3
Bad Rate Range: 40.00% -> 11.71%

====================================================================================================
MODEL: 727
====================================================================================================

----------------------------------------------------------------------------------------------------
MODEL = 727 | TARGET = TARGET_30
PERIOD <= 2026-05-09
----------------------------------------------------------------------------------------------------
   DECILE   cnt   bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  1994  356.0     17.85      -1423        517     1994     356.0
1       2  1949  274.0     14.06        520        560     3943     630.0
2       3  1970  203.0     10.30        562        597     5913     833.0
3       4  1909  152.0      7.96        600        627     7822     985.0
4       5  1739  112.0      6.44        630        650     9561    1097.0
5       6  1967   93.0      4.73        652        677    11528    1190.0
6       7  1729   64.0      3.70        680        700    13257    1254.0
7       8  2125   62.0      2.92        702        730    15382    1316.0
8       9  1700   36.0      2.12        737        767    17082    1352.0
9      10  1745   13.0      0.74        770        920    18827    1365.0

Monotonicity: PASS
Violations: 0
Bad Rate Range: 17.85% -> 0.74%

----------------------------------------------------------------------------------------------------
MODEL = 727 | TARGET = TARGET_60
PERIOD <= 2026-04-09
----------------------------------------------------------------------------------------------------
   DECILE   cnt   bads  bad_rate  min_score  max_score  cum_cnt  cum_bads
0       1  1942  117.0      6.02      -1423        517     1942     117.0
1       2  1928   74.0      3.84        520        560     3870     191.0
2       3  1944   65.0      3.34        567        597     5814     256.0
3       4  1887   48.0      2.54        600        627     7701     304.0
4       5  1731   27.0      1.56        630        650     9432     331.0

In [ ]:
# Decile tahlili bo‘yicha xulosalar
# SCORING_ID = 42
# Bad Rate umumiy pasayish trendini ko‘rsatsa-da, barcha targetlar bo‘yicha 3–4 ta monotonicity buzilishi mavjud. 
# Yuqori score segmentlarida risk pasaymoqda, biroq ayrim o‘rta decilelarda riskning qayta oshishi kuzatiladi. 
# Model risklarni to‘liq tartiblashda barqaror emas.
# 
# SCORING_ID = 122
# Monotonicity eng zaif modellardan biri hisoblanadi. TARGET_30 va TARGET_60 da 4 ta, TARGET_90 da esa 6 ta buzilish aniqlangan. 
# Bad Rate decilelar bo‘yicha notekis harakat qilmoqda, bu esa score va faktik risk o‘rtasidagi bog‘liqlikning sust ekanligini ko‘rsatadi.
# 
# SCORING_ID = 184
# Bad Rate birinchi va oxirgi decilelar orasida sezilarli farq ko‘rsatmoqda, biroq barcha targetlar bo‘yicha 3 tadan monotonicity buzilishi mavjud. 
# Model ma'lum darajada risklarni segmentatsiya qilmoqda, lekin decilelar bo‘yicha risk tartibi to‘liq saqlanmagan.
# 
# SCORING_ID = 343
# Decilelar bo‘yicha Bad Rate deyarli o‘zgarmaydi (TARGET_30 da 63–71% oralig‘ida). Monotonicity buzilishlari bilan birga decilelar orasidagi 
# farq juda kichik. Model ballari mijoz riskini deyarli ajratib bera olmayapti.
# 
# SCORING_ID = 504
# Bad Rate pastdan yuqoriga umumiy kamayish trendiga ega, ammo barcha targetlar bo‘yicha 3 tadan monotonicity buzilishi mavjud. 
# Ayrim o‘rta decilelarda riskning kutilmagan oshishi kuzatiladi. 
# 
# SCORING_ID = 727
# Decile tahlili bo‘yicha eng yaxshi natijalarni namoyish etgan model. TARGET_30 da monotonicity to‘liq saqlangan va buzilishlar mavjud emas. 
# TARGET_60 va TARGET_90 da faqat 1 tadan kichik buzilish kuzatiladi. Bad Rate birinchi deciledan oxirgi decilegacha izchil kamayib boradi, bu 
# score va faktik risk o‘rtasidagi kuchli bog‘liqlikni tasdiqlaydi.

In [12]:
df.groupby('SCORING_ID')['APPLICATION_DATE'].agg({min, max})

C:\Users\sh.nabiyev\AppData\Local\Temp\ipykernel_12048\985070687.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('SCORING_ID')['APPLICATION_DATE'].agg({min, max})
C:\Users\sh.nabiyev\AppData\Local\Temp\ipykernel_12048\985070687.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('SCORING_ID')['APPLICATION_DATE'].agg({min, max})

                  min        max
SCORING_ID
42         2022-07-19 2026-03-10
122        2022-10-17 2026-03-13
184        2023-01-06 2026-02-18
343        2024-02-09 2025-11-19
504        2024-06-19 2026-03-27
727        2025-01-22 2026-06-08

In [13]:
def calculate_psi(expected, actual, buckets=10):

    def get_bins(data):
        return np.linspace(data.min(), data.max(), buckets + 1)

    expected = np.array(expected)
    actual = np.array(actual)

    bin_edges = get_bins(expected)

    expected_counts, _ = np.histogram(expected, bins=bin_edges)
    actual_counts, _ = np.histogram(actual, bins=bin_edges)

    expected_perc = expected_counts / len(expected)
    actual_perc = actual_counts / len(actual)

    expected_perc = np.where(expected_perc == 0, 0.0001, expected_perc)
    actual_perc = np.where(actual_perc == 0, 0.0001, actual_perc)

    psi = np.sum((actual_perc - expected_perc) * np.log(actual_perc / expected_perc))

    return psi


# =========================
# SETTINGS
# =========================
max_date = df['APPLICATION_DATE'].max()

targets = {
    'TARGET_30': 30,
    'TARGET_60': 60,
    'TARGET_90': 90
}

summary = []


# =========================
# LOOP MODELS
# =========================
for scoring_id, df_model in df.groupby('SCORING_ID'):

    df_model = df_model.copy()
    df_model['APPLICATION_DATE'] = pd.to_datetime(df_model['APPLICATION_DATE'])

    # =========================
    # DEV / OOT SPLIT (GLOBAL PER MODEL)
    # =========================
    dates = np.sort(df_model['APPLICATION_DATE'].unique())

    if len(dates) < 10:
        continue

    split_date = dates[int(len(dates) * 0.7)]

    dev_df = df_model[df_model['APPLICATION_DATE'] <= split_date]
    oot_df = df_model[df_model['APPLICATION_DATE'] > split_date]

    for target, maturity_days in targets.items():

        # =========================
        # MATURITY FILTER (TARGET LEVEL ONLY)
        # =========================
        cutoff_date = max_date - pd.Timedelta(days=maturity_days)

        tmp = df_model.loc[
            df_model['APPLICATION_DATE'] <= cutoff_date,
            [target, 'SCORE_BALL']
        ].dropna()

        if len(tmp) < 100 or tmp[target].nunique() < 2:
            continue

        # =========================
        # AUC / GINI (CONSISTENT)
        # =========================
        auc = roc_auc_score(tmp[target], -tmp['SCORE_BALL'])
        gini = 2 * auc - 1

        # =========================
        # KS (FIXED DIRECTION)
        # =========================
        ks = ks_2samp(
            -tmp.loc[tmp[target] == 0, 'SCORE_BALL'],
            -tmp.loc[tmp[target] == 1, 'SCORE_BALL']
        ).statistic

        # =========================
        # MONOTONICITY (DECILE STABLE)
        # =========================
        tmp = tmp.copy()

        tmp['DECILE'] = pd.qcut(
            tmp['SCORE_BALL'],
            q=10,
            labels=False,
            duplicates='drop'
        ) + 1

        report = (
            tmp.groupby('DECILE')
            .agg(
                cnt=(target, 'count'),
                bads=(target, 'sum'),
                bad_rate=(target, 'mean')
            )
            .reset_index()
            .sort_values('DECILE')
        )

        report['bad_rate'] = report['bad_rate'] * 100

        monotonic = report['bad_rate'].is_monotonic_decreasing
        violations = (report['bad_rate'].diff() > 0).sum()

        # =========================
        # PSI (SAFE: SAME MODEL DISTRIBUTION ONLY)
        # =========================
        if len(dev_df) > 50 and len(oot_df) > 50:
            psi = calculate_psi(
                dev_df['SCORE_BALL'].dropna(),
                oot_df['SCORE_BALL'].dropna()
            )
        else:
            psi = np.nan

        # =========================
        # SAVE
        # =========================
        summary.append({
            'SCORING_ID': scoring_id,
            'TARGET': target,
            'OBS': len(tmp),
            'BAD_RATE': tmp[target].mean(),
            'AUC': auc,
            'GINI': gini,
            'KS': ks,
            'PSI': psi,
            'MONOTONIC': monotonic,
            'VIOLATIONS': violations,
            'DEV_START': dev_df['APPLICATION_DATE'].min(),
            'DEV_END': dev_df['APPLICATION_DATE'].max(),
            'OOT_START': oot_df['APPLICATION_DATE'].min(),
            'OOT_END': oot_df['APPLICATION_DATE'].max()
        })


summary_df = pd.DataFrame(summary)
summary_df

,SCORING_ID,TARGET,OBS,BAD_RATE,AUC,GINI,KS,PSI,MONOTONIC,VIOLATIONS,DEV_START,DEV_END,OOT_START,OOT_END
0,42,TARGET_30,2643,0.211124,0.545942,0.091884,0.077590,4.624665,False,3,2022-07-19,2024-03-06,2024-03-11,2026-03-10
1,42,TARGET_60,2643,0.069240,0.565131,0.130261,0.108563,4.624665,False,3,2022-07-19,2024-03-06,2024-03-11,2026-03-10
2,42,TARGET_90,2643,0.040106,0.541962,0.083924,0.078253,4.624665,False,4,2022-07-19,2024-03-06,2024-03-11,2026-03-10
3,122,TARGET_30,1272,0.308176,0.533602,0.067205,0.122124,0.488707,False,4,2022-10-17,2024-07-15,2024-07-16,2026-03-13
4,122,TARGET_60,1272,0.128931,0.539769,0.079538,0.159923,0.488707,False,4,2022-10-17,2024-07-15,2024-07-16,2026-03-13
5,122,TARGET_90,1271,0.081825,0.538424,0.076849,0.148820,0.488707,False,6,2022-10-17,2024-07-15,2024-07-16,2026-03-13
6,184,TARGET_30,6731,0.316149,0.567923,0.135846,0.117062,0.688074,False,3,2023-01-06,2025-03-03,2025-03-04,2026-02-18
7,184,TARGET_60,6731,0.157183,0.563953,0.127907,0.102537,0.688074,False,3,2023-01-06,2025-03-03,2025-03-04,2026-02-18
8,184,TARGET_90,6731,0.104145,0.563919,0.127838,0.096852,0.688074,False,3,2023-01-06,2025-03-03,2025-03-04,2026-02-18
9,343,TARGET_30,46728,0.689522,0.516976,0.033951,0.032126,2.504476,False,4,2024-02-09,2025-02-06,2025-02-07,2025-11-19
10,343,TARGET_60,46728,0.480954,0.513368,0.026737,0.026329,2.504476,False,4,2024-02-09,2025-02-06,2025-02-07,2025-11-19
11,343,TARGET_90,46728,0.378167,0.508259,0.016518,0.022254,2.504476,False,3,2024-02-09,2025-02-06,2025-02-07,2025-11-19
12,504,TARGET_30,1118,0.450805,0.604509,0.209018,0.156184,1.357034,False,3,2024-06-19,2025-03-12,2025-03-13,2026-03-27
13,504,TARGET_60,1118,0.322004,0.621132,0.242264,0.179544,1.357034,False,3,2024-06-19,2025-03-12,2025-03-13,2026-03-27
14,504,TARGET_90,1116,0.264337,0.615075,0.230149,0.165185,1.357034,False,3,2024-06-19,2025-03-12,2025-03-13,2026-03-27
15,727,TARGET_30,18827,0.072502,0.720185,0.440370,0.334232,0.214208,True,0,2025-01-22,2026-01-25,2026-01-26,2026-06-08
16,727,TARGET_60,18663,0.021272,0.730260,0.460521,0.368599,0.214208,False,1,2025-01-22,2026-01-25,2026-01-26,2026-06-08
17,727,TARGET_90,18505,0.011456,0.728304,0.456607,0.373838,0.214208,False,1,2025-01-22,2026-01-25,2026-01-26,2026-06-08

In [ ]:
# SCORING_ID = 42
# Modelning diskriminatsion ko‘rsatkichlari past (AUC 0.54–0.57, KS 0.08–0.11), decile tahlilida 3–4 ta monotonicity buzilishi mavjud. 
# PSI = 4.62 bo‘lib, development va OOT portfellar orasida juda katta taqsimot o‘zgarishi kuzatiladi. 
# Modelning ajratuvchanligi ham, stabiligi ham qoniqarsiz.
# 
# SCORING_ID = 122 
# AUC, GINI va KS qiymatlari past darajada. Decile tahlilida 4–6 ta monotonicity buzilishi aniqlangan. 
# PSI = 0.49 bo‘lib, model taqsimotida sezilarli drift mavjud. Modelning risklarni tartiblash qobiliyati va vaqt bo‘yicha barqarorligi cheklangan.
# 
# SCORING_ID = 184
# Model 42 va 122 ga nisbatan biroz yaxshiroq diskriminatsiya ko‘rsatmoqda, biroq GINI va KS hali ham past. 
# Barcha targetlar bo‘yicha 3 ta monotonicity buzilishi mavjud. PSI = 0.69 bo‘lib, sezilarli portfel o‘zgarishi kuzatiladi. 
# Modelning stabiligi qoniqarsiz baholanadi.
# 
# SCORING_ID = 343
# Modelning AUC (0.51–0.52), GINI (0.02–0.03) va KS (0.02–0.03) qiymatlari juda past. Decilelar bo‘yicha Bad Rate deyarli farqlanmaydi. 
# PSI = 2.50 bo‘lib, juda kuchli drift mavjud. Model risklarni ajratish va vaqt davomida barqaror ishlash nuqtai nazaridan eng zaif natijalarni ko‘rsatmoqda.
# 
# SCORING_ID = 504
# Modelning diskriminatsion ko‘rsatkichlari o‘rtacha darajada (AUC 0.60–0.62, KS 0.16–0.18). Decile tahlilida 3 ta monotonicity buzilishi mavjud. 
# PSI = 1.36 bo‘lib, development va OOT davrlari o‘rtasida katta taqsimot farqi mavjud. Modelning stabiligi past.
# 
# SCORING_ID = 727
# Tahlildagi eng yaxshi model. AUC (0.72–0.73), GINI (0.44–0.46) va KS (0.33–0.37) boshqa modellarga nisbatan ancha yuqori. 
# TARGET_30 bo‘yicha monotonicity to‘liq saqlangan, TARGET_60 va TARGET_90 da esa faqat bittadan buzilish mavjud. PSI = 0.21 bo‘lib, 
# model taqsimoti nisbatan barqaror. Diskriminatsiya va stabilik nuqtai nazaridan eng yaxshi natijalar ushbu modelda kuzatiladi.

In [14]:
def calculate_psi(expected, actual, buckets=10):

    expected = np.array(expected)
    actual = np.array(actual)

    # =========================
    # GLOBAL BIN BASED ON COMBINED DISTRIBUTION (FIX)
    # =========================
    combined = np.concatenate([expected, actual])
    bin_edges = np.linspace(combined.min(), combined.max(), buckets + 1)

    expected_counts, _ = np.histogram(expected, bins=bin_edges)
    actual_counts, _ = np.histogram(actual, bins=bin_edges)

    expected_perc = expected_counts / len(expected)
    actual_perc = actual_counts / len(actual)

    expected_perc = np.where(expected_perc == 0, 0.0001, expected_perc)
    actual_perc = np.where(actual_perc == 0, 0.0001, actual_perc)

    psi = np.sum((actual_perc - expected_perc) * np.log(actual_perc / expected_perc))

    return psi

all_psi_score = {}

for scoring_id, df_model in df.groupby('SCORING_ID'):

    df_model = df_model.copy()
    df_model['APPLICATION_DATE'] = pd.to_datetime(df_model['APPLICATION_DATE'])

    dates = np.sort(df_model['APPLICATION_DATE'].unique())

    if len(dates) < 10:
        continue

    split_date = dates[int(len(dates) * 0.7)]

    dev_df = df_model[df_model['APPLICATION_DATE'] <= split_date]
    oot_df = df_model[df_model['APPLICATION_DATE'] > split_date]

    if len(dev_df) < 100 or len(oot_df) < 100:
        continue

    psi = calculate_psi(
        dev_df['SCORE_BALL'].dropna(),
        oot_df['SCORE_BALL'].dropna()
    )

    all_psi_score[scoring_id] = psi

    print(f"\nMODEL {scoring_id} | SCORE PSI = {psi:.4f}")

MODEL 42 | SCORE PSI = 4.6247

MODEL 122 | SCORE PSI = 0.4582

MODEL 184 | SCORE PSI = 0.6881

MODEL 343 | SCORE PSI = 2.4028

MODEL 504 | SCORE PSI = 1.4819

MODEL 727 | SCORE PSI = 0.2142

In [15]:
all_psi_time = {}

for scoring_id, df_model in df.groupby('SCORING_ID'):

    df_model = df_model.copy()
    df_model['APPLICATION_DATE'] = pd.to_datetime(df_model['APPLICATION_DATE'])

    df_model['MONTH'] = df_model['APPLICATION_DATE'].dt.to_period('M')

    months = sorted(df_model['MONTH'].unique())

    results = []

    for i in range(1, len(months)):

        prev = df_model[df_model['MONTH'] == months[i-1]]['SCORE_BALL'].dropna()
        curr = df_model[df_model['MONTH'] == months[i]]['SCORE_BALL'].dropna()

        if len(prev) < 50 or len(curr) < 50:
            continue

        # =========================
        # FIX: GLOBAL BIN CONSISTENCY
        # =========================
        psi = calculate_psi(prev, curr)

        results.append({
            'MONTH': str(months[i]),
            'PSI': psi,
            'OBS_PREV': len(prev),
            'OBS_CURR': len(curr)
        })

    psi_df = pd.DataFrame(results)

    all_psi_time[scoring_id] = psi_df

    print("\n" + "="*60)
    print(f"MODEL {scoring_id} - TIME PSI")
    print("="*60)

    print(psi_df)

============================================================
MODEL 42 - TIME PSI
============================================================
     MONTH       PSI  OBS_PREV  OBS_CURR
0  2022-09  0.164437       166       255
1  2022-10  0.064444       255       257
2  2022-11  0.073052       257       387
3  2022-12  0.504938       387       342
4  2023-01  0.828048       342        87
5  2023-02  0.271650        87       109
6  2023-03  3.429782       109        82
7  2023-09  0.127056       275        61
8  2024-05  0.241962        64        76
9  2024-06  0.089646        76        89

============================================================
MODEL 122 - TIME PSI
============================================================
     MONTH       PSI  OBS_PREV  OBS_CURR
0  2022-12  0.410690        58        55
1  2023-06  0.460844        90        67
2  2023-07  0.149157        67        69
3  2023-08  0.080110        69       172
4  2023-09  0.192904       172       120
5  2023-10  0.279798       120        53

============================================================
MODEL 184 - TIME PSI
============================================================
      MONTH       PSI  OBS_PREV  OBS_CURR
0   2023-02  0.096341       152       394
1   2023-03  0.113681       394       117
2   2023-06  0.179888       111       283
3   2023-07  0.478001       283       237
4   2023-08  0.067823       237       229
5   2023-09  0.135696       229       155
6   2024-02  0.106332       107       115
7   2024-03  0.505478       115       100
8   2024-04  0.868577       100        92
9   2024-05  0.950660        92       227
10  2024-06  0.274905       227       367
11  2024-07  0.169282       367       276
12  2024-08  0.167178       276       411
13  2024-09  0.110641       411       247
14  2024-10  0.069185       247       334
15  2024-11  0.025812       334       349
16  2024-12  0.138919       349       291
17  2025-01  1.003801       291       488
18  2025-02  0.049927       488       408
19  2025-03  1.773449       408       304
20  2025-04  0.376486       304       304
21  2025-05  0.124487       304       113
22  2025-06  0.123970       113        94
23  2025-07  0.374473        94        95
24  2025-08  0.728601        95        63
25  2025-09  0.505374        63        54
26  2025-10  0.417778        54        55

============================================================
MODEL 343 - TIME PSI
============================================================
      MONTH       PSI  OBS_PREV  OBS_CURR
0   2024-03  0.039530       508      1743
1   2024-04  0.084903      1743      5106
2   2024-05  0.229258      5106      2762
3   2024-06  0.033128      2762      2369
4   2024-07  0.357676      2369      3394
5   2024-08  0.012544      3394      3611
6   2024-09  0.006160      3611      3007
7   2024-10  0.008756      3007      2442
8   2024-11  0.033535      2442      1656
9   2024-12  1.099211      1656       874
10  2025-01  1.104978       874      2924
11  2025-02  0.003374      2924      7083
12  2025-03  0.004422      7083      7043
13  2025-04  6.875963      7043      1321
14  2025-10  0.439261        85       433
15  2025-11  0.073887       433       346

============================================================
MODEL 504 - TIME PSI
============================================================
     MONTH       PSI  OBS_PREV  OBS_CURR
0  2024-08  0.233168        84        78
1  2024-09  0.332888        78        59
2  2024-10  0.375598        59        69
3  2024-11  0.824337        69        61
4  2024-12  0.895586        61        94
5  2025-01  0.292268        94        96
6  2025-02  0.165823        96       166
7  2025-03  2.229111       166       211
8  2025-04  0.233633       211       102

============================================================
MODEL 727 - TIME PSI
============================================================
      MONTH           PSI  OBS_PREV  OBS_CURR
0   2025-05  4.768892e-04      1462      2372
1   2025-06  4.857479e-07      2372      2326
2   2025-07  1.524158e-03      2326      2388
3   2025-08  5.748689e-03      2388      2363
4   2025-09  9.807711e-03      2363      2113
5   2025-10  8.076317e-03      2113      2394
6   2025-11  2.684949e-02      2394      1733
7   2025-12  1.794813e-02      1733       794
8   2026-01  8.329350e-02       794       239
9   2026-02  2.301625e-01       239       218
10  2026-03  1.405439e-01       218       171
11  2026-04  5.497252e-01       171       164
12  2026-05  2.117608e-01       164       128

In [ ]:
# SCORING_ID = 42
# Vaqt bo‘yicha PSI tahlili model taqsimotining yuqori darajada o‘zgaruvchan ekanligini ko‘rsatadi. Bir nechta davrlarda PSI 0.5 dan, ayrim oylarda 
# esa 1.0 va hatto 3.4 dan yuqori qiymatlarni olgan. Kuzatilgan keskin o‘zgarishlar modelning vaqt bo‘yicha stabil emasligini ko‘rsatadi.
# 
# SCORING_ID = 122
# Modelda PSI ko‘rsatkichlari ko‘p hollarda 0.1–0.5 oralig‘ida shakllangan. Ayrim davrlarda 0.4 dan yuqori qiymatlar kuzatilgan bo‘lib, bu 
# portfel tarkibida sezilarli o‘zgarishlar mavjudligini bildiradi. Umumiy baholashda model stabiligi o‘rtacha-past darajada.
# 
# SCORING_ID = 184
# Modelda PSI qiymatlari tez-tez 0.25 dan yuqori va bir qator davrlarda 0.5–1.7 oralig‘iga chiqadi. Vaqt davomida score taqsimotining sezilarli 
# siljishi kuzatilgan. Modelning stabiligi qoniqarli emas va drift riski yuqori.
# 
# SCORING_ID = 343
# Ayrim davrlarda PSI juda past bo‘lsa-da, bir nechta keskin sakrashlar (1.1 va 6.88 gacha) aniqlangan. Bu model portfeli tarkibida katta 
# strukturaviy o‘zgarishlar bo‘lganligini ko‘rsatadi. Model vaqt bo‘yicha barqaror emas.
# 
# SCORING_ID = 504
# PSI ko‘rsatkichlari aksariyat davrlarda 0.2–0.9 oralig‘ida shakllangan va 2.23 gacha yetgan holatlar mavjud. Bu score taqsimotida sezilarli 
# drift mavjudligini ko‘rsatadi. Model stabiligi past baholanadi.
# 
# SCORING_ID = 727
# Model eng barqaror natijalarni namoyish etgan. PSI qiymatlari uzoq vaqt davomida 0.01 dan ham past darajada saqlangan. Faqat oxirgi davrlarda 
# kuzatuvlar sonining kamayishi fonida ayrim oylarda 0.2–0.55 gacha oshish kuzatiladi. Shunga qaramay, boshqa modellarga nisbatan vaqt 
# bo‘yicha eng yuqori stabilik ushbu modelda kuzatilgan.

In [16]:
def make_lift_table(df_model, target, cutoff_date, n_bins=10):

    tmp = df_model.loc[
        df_model['APPLICATION_DATE'] <= cutoff_date,
        [target, 'SCORE_BALL']
    ].dropna().copy()

    if len(tmp) < 100 or tmp[target].nunique() < 2:
        return None

    # =========================
    # DECILE (HIGH SCORE = BETTER ASSUMPTION FIXED)
    # =========================
    tmp['DECILE'] = pd.qcut(
        tmp['SCORE_BALL'],
        q=n_bins,
        labels=False,
        duplicates='drop'
    ) + 1

    lift = (
        tmp.groupby('DECILE')
        .agg(
            cnt=(target, 'count'),
            bads=(target, 'sum'),
            bad_rate=(target, 'mean')
        )
        .reset_index()
        .sort_values('DECILE')
    )

    lift['bad_rate'] = lift['bad_rate'] * 100

    overall_bad_rate = tmp[target].mean()

    # =========================
    # LIFT (FIXED + SAFE)
    # =========================
    lift['lift'] = lift['bad_rate'] / (overall_bad_rate * 100)

    # normalize again for stability
    lift['lift'] = lift['lift'].replace([np.inf, -np.inf], np.nan)

    return lift, overall_bad_rate
all_lift = {}

for scoring_id, df_model in df.groupby('SCORING_ID'):

    print("\n" + "="*80)
    print(f"MODEL: {scoring_id}")
    print("="*80)

    for target, maturity_days in targets.items():

        cutoff_date = max_date - pd.Timedelta(days=maturity_days)

        result = make_lift_table(df_model, target, cutoff_date)

        if result is None:
            print(f"{target}: data yo'q")
            continue

        lift_df, overall_br = result

        all_lift[(scoring_id, target)] = lift_df

        print("\n" + "-"*60)
        print(f"{target} | Overall Bad Rate = {overall_br:.4f}")
        print("-"*60)

        print(lift_df)

        # =========================
        # SAFE TOP LIFT
        # =========================
        if 1 in lift_df['DECILE'].values:
            top_lift = lift_df.loc[lift_df['DECILE'] == 1, 'lift'].values[0]
        else:
            top_lift = lift_df['lift'].max()

        print(f"\nTOP LIFT (worst decile): {top_lift:.2f}x")

================================================================================
MODEL: 42
================================================================================

------------------------------------------------------------
TARGET_30 | Overall Bad Rate = 0.2111
------------------------------------------------------------
   DECILE  cnt  bads   bad_rate      lift
0       1  272  81.0  29.779412  1.410519
1       2  350  73.0  20.857143  0.987911
2       3  211  52.0  24.644550  1.167304
3       4  282  60.0  21.276596  1.007779
4       5  233  41.0  17.596567  0.833472
5       6  269  47.0  17.472119  0.827577
6       7  253  56.0  22.134387  1.048408
7       8  280  66.0  23.571429  1.116475
8       9  254  52.0  20.472441  0.969689
9      10  239  30.0  12.552301  0.594547

TOP LIFT (worst decile): 1.41x

------------------------------------------------------------
TARGET_60 | Overall Bad Rate = 0.0692
------------------------------------------------------------
   DECILE  cnt  bads   bad_rate      lift
0       1  272  31.0  11.397059  1.646034
1       2  350  27.0   7.714286  1.114145
2       3  211  18.0   8.530806  1.232072
3       4  282  16.0   5.673759  0.819440
4       5  233  14.0   6.008584  0.867797
5       6  269  15.0   5.576208  0.805351
6       7  253  14.0   5.533597  0.799197
7       8  280  23.0   8.214286  1.186358
8       9  254  20.0   7.874016  1.137214
9      10  239   5.0   2.092050  0.302147

TOP LIFT (worst decile): 1.65x

------------------------------------------------------------
TARGET_90 | Overall Bad Rate = 0.0401
------------------------------------------------------------
   DECILE  cnt  bads  bad_rate      lift
0       1  272  18.0  6.617647  1.650042
1       2  350  10.0  2.857143  0.712399
2       3  211  11.0  5.213270  1.299875
3       4  282  11.0  3.900709  0.972601
4       5  233   8.0  3.433476  0.856102
5       6  269  12.0  4.460967  1.112296
6       7  253   7.0  2.766798  0.689872
7       8  280  12.0  4.285714  1.068598
8       9  254  14.0  5.511811  1.374313
9      10  239   3.0  1.255230  0.312979

TOP LIFT (worst decile): 1.65x

================================================================================
MODEL: 122
================================================================================

------------------------------------------------------------
TARGET_30 | Overall Bad Rate = 0.3082
------------------------------------------------------------
   DECILE  cnt  bads   bad_rate      lift
0       1  142  37.0  26.056338  0.845502
1       2  126  39.0  30.952381  1.004373
2       3  122  45.0  36.885246  1.196889
3       4  165  57.0  34.545455  1.120965
4       5   96  29.0  30.208333  0.980230
5       6  128  53.0  41.406250  1.343591
6       7  137  46.0  33.576642  1.089528
7       8  109  43.0  39.449541  1.280097
8       9  142  27.0  19.014085  0.616988
9      10  105  16.0  15.238095  0.494461

TOP LIFT (worst decile): 0.85x

------------------------------------------------------------
TARGET_60 | Overall Bad Rate = 0.1289
------------------------------------------------------------
   DECILE  cnt  bads   bad_rate      lift
0       1  142  14.0   9.859155  0.764686
1       2  126  14.0  11.111111  0.861789
2       3  122  20.0  16.393443  1.271491
3       4  165  27.0  16.363636  1.269180
4       5   96  14.0  14.583333  1.131098
5       6  128  23.0  17.968750  1.393674
6       7  137  20.0  14.598540  1.132277
7       8  109  23.0  21.100917  1.636608
8       9  142   8.0   5.633803  0.436963
9      10  105   1.0   0.952381  0.073868

TOP LIFT (worst decile): 0.76x

------------------------------------------------------------
TARGET_90 | Overall Bad Rate = 0.0818
------------------------------------------------------------
   DECILE  cnt  bads   bad_rate      lift
0       1  142   6.0   4.225352  0.516387
1       2  126  11.0   8.730159  1.066926
2       3  121  12.0   9.917355  1.212015
3       4  165  21.0  12.727273  1.555420
4       5   96   8.0   8.333333  1.018429
5       6  128  13.0  10.156250  1.241211
6       7  137  15.0  10.948905  1.338083
7       8  109  12.0  11.009174  1.345448
8       9  142   5.0   3.521127  0.430322
9      10  105   1.0   0.952381  0.116392

TOP LIFT (worst decile): 0.52x

================================================================================
MODEL: 184
================================================================================

------------------------------------------------------------
TARGET_30 | Overall Bad Rate = 0.3161
------------------------------------------------------------
   DECILE  cnt   bads   bad_rate      lift
0       1  752  303.0  40.292553  1.274479
1       2  611  231.0  37.806874  1.195856
2       3  723  271.0  37.482711  1.185602
3       4  628  219.0  34.872611  1.103043
4       5  731  200.0  27.359781  0.865407
5       6  784  217.0  27.678571  0.875491
6       7  585  187.0  31.965812  1.011099
7       8  813  216.0  26.568266  0.840371
8       9  528  165.0  31.250000  0.988457
9      10  576  119.0  20.659722  0.653480

TOP LIFT (worst decile): 1.27x

------------------------------------------------------------
TARGET_60 | Overall Bad Rate = 0.1572
------------------------------------------------------------
   DECILE  cnt   bads   bad_rate      lift
0       1  752  153.0  20.345745  1.294397
1       2  611  112.0  18.330606  1.166194
2       3  723  143.0  19.778700  1.258322
3       4  628  105.0  16.719745  1.063711
4       5  731  104.0  14.227086  0.905128
5       6  784  109.0  13.903061  0.884513
6       7  585   95.0  16.239316  1.033146
7       8  813  109.0  13.407134  0.852962
8       9  528   79.0  14.962121  0.951891
9      10  576   49.0   8.506944  0.541212

TOP LIFT (worst decile): 1.29x

------------------------------------------------------------
TARGET_90 | Overall Bad Rate = 0.1041
------------------------------------------------------------
   DECILE  cnt   bads   bad_rate      lift
0       1  752  102.0  13.563830  1.302399
1       2  611   75.0  12.274959  1.178641
2       3  723   95.0  13.139696  1.261673
3       4  628   66.0  10.509554  1.009127
4       5  731   72.0   9.849521  0.945751
5       6  784   76.0   9.693878  0.930806
6       7  585   66.0  11.282051  1.083302
7       8  813   68.0   8.364084  0.803119
8       9  528   51.0   9.659091  0.927466
9      10  576   30.0   5.208333  0.500104

TOP LIFT (worst decile): 1.30x

================================================================================
MODEL: 343
================================================================================

------------------------------------------------------------
TARGET_30 | Overall Bad Rate = 0.6895
------------------------------------------------------------
   DECILE   cnt    bads   bad_rate      lift
0       1  5272  3707.0  70.314871  1.019762
1       2  4107  2792.0  67.981495  0.985922
2       3  6107  4277.0  70.034387  1.015694
3       4  4172  2964.0  71.045062  1.030352
4       5  3784  2646.0  69.926004  1.014122
5       6  6002  4164.0  69.376874  1.006158
6       7  4034  2837.0  70.327219  1.019941
7       8  5736  3917.0  68.288006  0.990367
8       9  3012  2058.0  68.326693  0.990928
9      10  4502  2858.0  63.482896  0.920679

TOP LIFT (worst decile): 1.02x

------------------------------------------------------------
TARGET_60 | Overall Bad Rate = 0.4810
------------------------------------------------------------
   DECILE   cnt    bads   bad_rate      lift
0       1  5272  2613.0  49.563733  1.030530
1       2  4107  1944.0  47.333820  0.984166
2       3  6107  3033.0  49.664320  1.032622
3       4  4172  2099.0  50.311601  1.046080
4       5  3784  1780.0  47.040169  0.978060
5       6  6002  2851.0  47.500833  0.987639
6       7  4034  2009.0  49.801686  1.035478
7       8  5736  2766.0  48.221757  1.002628
8       9  3012  1432.0  47.543161  0.988519
9      10  4502  1947.0  43.247446  0.899202

TOP LIFT (worst decile): 1.03x

------------------------------------------------------------
TARGET_90 | Overall Bad Rate = 0.3782
------------------------------------------------------------
   DECILE   cnt    bads   bad_rate      lift
0       1  5272  2025.0  38.410470  1.015701
1       2  4107  1523.0  37.083029  0.980599
2       3  6107  2405.0  39.381038  1.041366
3       4  4172  1627.0  38.998082  1.031239
4       5  3784  1372.0  36.257928  0.958780
5       6  6002  2230.0  37.154282  0.982483
6       7  4034  1588.0  39.365394  1.040952
7       8  5736  2234.0  38.947001  1.029888
8       9  3012  1144.0  37.981408  1.004355
9      10  4502  1523.0  33.829409  0.894562

TOP LIFT (worst decile): 1.02x

================================================================================
MODEL: 504
================================================================================

------------------------------------------------------------
TARGET_30 | Overall Bad Rate = 0.4508
------------------------------------------------------------
   DECILE  cnt  bads   bad_rate      lift
0       1  122  77.0  63.114754  1.400046
1       2  121  66.0  54.545455  1.209957
2       3  132  61.0  46.212121  1.025102
3       4  129  55.0  42.635659  0.945767
4       5   79  41.0  51.898734  1.151246
5       6  119  54.0  45.378151  1.006603
6       7   85  44.0  51.764706  1.148273
7       8  120  38.0  31.666667  0.702447
8       9  100  34.0  34.000000  0.754206
9      10  111  34.0  30.630631  0.679465

TOP LIFT (worst decile): 1.40x

------------------------------------------------------------
TARGET_60 | Overall Bad Rate = 0.3220
------------------------------------------------------------
   DECILE  cnt  bads   bad_rate      lift
0       1  122  62.0  50.819672  1.578233
1       2  121  53.0  43.801653  1.360285
2       3  132  46.0  34.848485  1.082239
3       4  129  39.0  30.232558  0.938889
4       5   79  27.0  34.177215  1.061392
5       6  119  32.0  26.890756  0.835107
6       7   85  34.0  40.000000  1.242222
7       8  120  26.0  21.666667  0.672870
8       9  100  23.0  23.000000  0.714278
9      10  111  18.0  16.216216  0.503604

TOP LIFT (worst decile): 1.58x

------------------------------------------------------------
TARGET_90 | Overall Bad Rate = 0.2643
------------------------------------------------------------
   DECILE  cnt  bads   bad_rate      lift
0       1  122  48.0  39.344262  1.488413
1       2  120  48.0  40.000000  1.513220
2       3  132  34.0  25.757576  0.974422
3       4  128  32.0  25.000000  0.945763
4       5   79  25.0  31.645570  1.197168
5       6  119  26.0  21.848739  0.826549
6       7   85  30.0  35.294118  1.335194
7       8  120  23.0  19.166667  0.725085
8       9  100  16.0  16.000000  0.605288
9      10  111  13.0  11.711712  0.443060

TOP LIFT (worst decile): 1.49x

================================================================================
MODEL: 727
================================================================================

------------------------------------------------------------
TARGET_30 | Overall Bad Rate = 0.0725
------------------------------------------------------------
   DECILE   cnt   bads   bad_rate      lift
0       1  1994  356.0  17.853561  2.462483
1       2  1949  274.0  14.058492  1.939042
2       3  1970  203.0  10.304569  1.421276
3       4  1909  152.0   7.962284  1.098212
4       5  1739  112.0   6.440483  0.888315
5       6  1967   93.0   4.728012  0.652119
6       7  1729   64.0   3.701562  0.510544
7       8  2125   62.0   2.917647  0.402422
8       9  1700   36.0   2.117647  0.292080
9      10  1745   13.0   0.744986  0.102753

TOP LIFT (worst decile): 2.46x

------------------------------------------------------------
TARGET_60 | Overall Bad Rate = 0.0213
------------------------------------------------------------
   DECILE   cnt   bads  bad_rate      lift
0       1  1942  117.0  6.024717  2.832224
1       2  1928   74.0  3.838174  1.804329
2       3  1944   65.0  3.343621  1.571839
3       4  1887   48.0  2.543720  1.195805
4       5  1731   27.0  1.559792  0.733259
5       6  1953   23.0  1.177675  0.553626
6       7  1721   13.0  0.755375  0.355102
7       8  2120   15.0  0.707547  0.332618
8       9  1694   13.0  0.767414  0.360762
9      10  1743    2.0  0.114745  0.053942

TOP LIFT (worst decile): 2.83x

------------------------------------------------------------
TARGET_90 | Overall Bad Rate = 0.0115
------------------------------------------------------------
   DECILE   cnt  bads  bad_rate      lift
0       1  1903  57.0  2.995271  2.614504
1       2  1908  43.0  2.253669  1.967176
2       3  1928  37.0  1.919087  1.675128
3       4  1871  27.0  1.443079  1.259631
4       5  1714  17.0  0.991832  0.865748
5       6  1940   9.0  0.463918  0.404943
6       7  1717   6.0  0.349447  0.305024
7       8  2111   6.0  0.284225  0.248094
8       9  1682   9.0  0.535077  0.467057
9      10  1731   1.0  0.057770  0.050426

TOP LIFT (worst decile): 2.61x

In [ ]:
# Modellar bo‘yicha lift xulosasi
# Model 343
# Lift ≈ 1.0x
# Eng yomon holat: decilelar deyarli farqlanmagan
# Xulosa: Model riskni umuman ajrata olmaydi (randomga yaqin). Ishlatishga yaroqsiz.
# 
# Model 122
# Lift ≈ 0.5x – 1.3x
# Ba’zi targetlarda hatto 1.0 dan past
# Xulosa: Ranking noto‘g‘ri ishlayapti, model signal bermaydi yoki teskari ishlash holatlari bor.
# 
# Model 184
# Lift ≈ 1.2x – 1.3x
# Past–o‘rtacha ajratish qobiliyati
# Xulosa: Minimal biznes qiymat bor, lekin kuchsiz model. Faqat support-level model sifatida qolishi mumkin.
# 
# Model 42
# Lift ≈ 1.4x – 1.6x
# O‘rtacha past segmentatsiya
# Xulosa: Riskni qisman ajratadi, lekin kuchli qarorlar uchun yetarli emas.
# 
# Model 504
# Lift ≈ 1.4x – 1.6x
# Segmentatsiya mavjud, lekin noturg‘un (PSI yuqori)
# Xulosa: Ajratish bor, lekin stability muammo. Monitoring shart.
# 
# Model 727
# Lift ≈ 2.5x – 2.8x
# Juda kuchli separation
# Xulosa: Eng yaxshi model. Top risk segment aniq ajralgan. Production uchun mos.

In [17]:
def time_based_metrics(df_model, target, score_col='SCORE_BALL', date_col='APPLICATION_DATE'):

    df_model = df_model.copy()
    df_model[date_col] = pd.to_datetime(df_model[date_col])

    # =========================
    # SAFE MONTH FORMAT (KEEP PERIOD, NOT STRING)
    # =========================
    df_model['MONTH'] = df_model[date_col].dt.to_period('M')

    results = []

    months = sorted(df_model['MONTH'].unique())

    for month in months:

        tmp = df_model[df_model['MONTH'] == month].dropna(subset=[target, score_col])

        # =========================
        # STRONG SAMPLE FILTER
        # =========================
        if len(tmp) < 50 or tmp[target].nunique() < 2:
            continue

        # =========================
        # AUC / GINI (CONSISTENT)
        # =========================
        auc = roc_auc_score(tmp[target], -tmp[score_col])
        gini = 2 * auc - 1

        # =========================
        # KS (CONSISTENT SIGN)
        # =========================
        ks = ks_2samp(
            -tmp.loc[tmp[target] == 0, score_col],
            -tmp.loc[tmp[target] == 1, score_col]
        ).statistic

        results.append({
            'MONTH': month,   # keep PERIOD (IMPORTANT FIX)
            'OBS': len(tmp),
            'BAD_RATE': tmp[target].mean(),
            'AUC': auc,
            'GINI': gini,
            'KS': ks
        })

    return pd.DataFrame(results)


all_time_metrics = {}

for scoring_id, df_model in df.groupby('SCORING_ID'):

    df_model = df_model.copy()
    df_model['APPLICATION_DATE'] = pd.to_datetime(df_model['APPLICATION_DATE'])

    print("\n" + "="*90)
    print(f"MODEL: {scoring_id}")
    print("="*90)

    for target, maturity_days in targets.items():

        cutoff_date = max_date - pd.Timedelta(days=maturity_days)

        tmp_model = df_model[df_model['APPLICATION_DATE'] <= cutoff_date]

        if len(tmp_model) < 100:
            print(f"\n{target}: insufficient data")
            continue

        time_df = time_based_metrics(tmp_model, target)

        if time_df.empty:
            print(f"\n{target}: no valid monthly segments")
            continue

        all_time_metrics[(scoring_id, target)] = time_df

        print("\n" + "-"*70)
        print(f"{target} | OBS = {len(tmp_model):,}")
        print("-"*70)

        print(time_df)

==========================================================================================
MODEL: 42
==========================================================================================

----------------------------------------------------------------------
TARGET_30 | OBS = 2,643
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2022-08  166  0.253012  0.689324  0.378648  0.337174
1   2022-09  255  0.227451  0.586863  0.173727  0.150971
2   2022-10  257  0.210117  0.653758  0.307517  0.254242
3   2022-11  387  0.183463  0.593978  0.187957  0.152656
4   2022-12  342  0.213450  0.482864 -0.034272  0.102460
5   2023-01   87  0.218391  0.541022  0.082043  0.175697
6   2023-02  109  0.256881  0.597222  0.194444  0.176808
7   2023-03   82  0.219512  0.502170  0.004340  0.140625
8   2023-05   59  0.220339  0.612876  0.225753  0.314381
9   2023-08  275  0.214545  0.558027  0.116055  0.128923
10  2023-09   61  0.131148  0.472877 -0.054245  0.297170
11  2024-04   64  0.234375  0.653061  0.306122  0.248980
12  2024-05   76  0.223684  0.666500  0.333001  0.276171
13  2024-06   89  0.213483  0.701880  0.403759  0.407519

----------------------------------------------------------------------
TARGET_60 | OBS = 2,643
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2022-08  166  0.102410  0.638571  0.277142  0.276747
1   2022-09  255  0.047059  0.641632  0.283265  0.319959
2   2022-10  257  0.046693  0.801531  0.603061  0.639116
3   2022-11  387  0.077519  0.620495  0.240990  0.210644
4   2022-12  342  0.090643  0.471372 -0.057255  0.140857
5   2023-01   87  0.103448  0.584758  0.169516  0.316239
6   2023-02  109  0.082569  0.560000  0.120000  0.223333
7   2023-03   82  0.048780  0.724359  0.448718  0.551282
8   2023-05   59  0.135593  0.607843  0.215686  0.343137
9   2023-08  275  0.050909  0.578544  0.157088  0.200602
10  2023-09   61  0.049180  0.500000  0.000000  0.431034
11  2024-04   64  0.078125  0.774576  0.549153  0.627119
12  2024-05   76  0.065789  0.925352  0.850704  0.859155
13  2024-06   89  0.067416  0.845382  0.690763  0.616466

----------------------------------------------------------------------
TARGET_90 | OBS = 2,643
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2022-08  166  0.048193  0.700949  0.401899  0.351266
1   2022-09  255  0.027451  0.655530  0.311060  0.301267
2   2022-10  257  0.023346  0.738048  0.476096  0.538513
3   2022-11  387  0.038760  0.551075  0.102151  0.202151
4   2022-12  342  0.064327  0.449219 -0.101562  0.194602
5   2023-01   87  0.091954  0.648734  0.297468  0.419304
6   2023-02  109  0.027523  0.234277 -0.531447  0.613208
7   2023-03   82  0.024390  0.790625  0.581250  0.675000
8   2023-05   59  0.067797  0.402273 -0.195455  0.386364
9   2023-08  275  0.032727  0.588972  0.177945  0.205931
10  2023-09   61  0.032787  0.525424  0.050847  0.423729
11  2024-04   64  0.031250  0.693548  0.387097  0.661290
12  2024-05   76  0.039474  0.922374  0.844749  0.876712
13  2024-06   89  0.033708  0.800388  0.600775  0.593023

==========================================================================================
MODEL: 122
==========================================================================================

----------------------------------------------------------------------
TARGET_30 | OBS = 1,272
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2022-11   58  0.206897  0.475543 -0.048913  0.184783
1   2022-12   55  0.254545  0.382404 -0.235192  0.365854
2   2023-05   90  0.300000  0.502939  0.005879  0.158730
3   2023-06   67  0.432836  0.546279  0.092559  0.163339
4   2023-07   69  0.347826  0.559259  0.118519  0.186111
5   2023-08  172  0.250000  0.534703  0.069407  0.162791
6   2023-09  120  0.391667  0.587875  0.175751  0.214806
7   2023-10   53  0.283019  0.566667  0.133333  0.242105
8   2024-01  107  0.392523  0.515934  0.031868  0.152381
9   2024-03   53  0.320755  0.619281  0.238562  0.295752
10  2024-05   57  0.315789  0.732194  0.464387  0.457265

----------------------------------------------------------------------
TARGET_60 | OBS = 1,272
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2022-11   58  0.034483  0.513393  0.026786  0.464286
1   2022-12   55  0.109091  0.403061 -0.193878  0.306122
2   2023-05   90  0.166667  0.470222 -0.059556  0.173333
3   2023-06   67  0.149254  0.551754  0.103509  0.238596
4   2023-07   69  0.159420  0.715517  0.431034  0.377743
5   2023-08  172  0.122093  0.589246  0.178493  0.242826
6   2023-09  120  0.200000  0.529080  0.058160  0.208333
7   2023-10   53  0.169811  0.710859  0.421717  0.396465
8   2024-01  107  0.186916  0.480172 -0.039655  0.172414
9   2024-03   53  0.150943  0.540278  0.080556  0.180556
10  2024-05   57  0.070175  0.676887  0.353774  0.490566

----------------------------------------------------------------------
TARGET_90 | OBS = 1,271
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2022-11   58  0.034483  0.513393  0.026786  0.464286
1   2022-12   55  0.054545  0.358974 -0.282051  0.358974
2   2023-05   90  0.100000  0.532236  0.064472  0.185185
3   2023-06   67  0.119403  0.522246  0.044492  0.173729
4   2023-07   69  0.101449  0.733871  0.467742  0.486175
5   2023-08  172  0.081395  0.609177  0.218354  0.283906
6   2023-09  120  0.125000  0.543810  0.087619  0.219048
7   2023-10   53  0.150943  0.665278  0.330556  0.322222
8   2024-01  107  0.149533  0.518544  0.037088  0.182005
9   2024-03   53  0.075472  0.448980 -0.102041  0.255102
10  2024-05   57  0.035088  0.650000  0.300000  0.472727

==========================================================================================
MODEL: 184
==========================================================================================

----------------------------------------------------------------------
TARGET_30 | OBS = 6,731
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2023-01  152  0.361842  0.554733  0.109466  0.125961
1   2023-02  394  0.398477  0.557741  0.115483  0.123895
2   2023-03  117  0.478632  0.624268  0.248536  0.181499
3   2023-05  111  0.297297  0.628594  0.257187  0.248252
4   2023-06  283  0.293286  0.497982 -0.004036  0.087651
5   2023-07  237  0.341772  0.562441  0.124881  0.161206
6   2023-08  229  0.314410  0.554804  0.109607  0.116773
7   2023-09  155  0.387097  0.547281  0.094561  0.134211
8   2024-01  107  0.411215  0.696068  0.392136  0.366883
9   2024-02  115  0.400000  0.525992  0.051985  0.115942
10  2024-03  100  0.530000  0.645925  0.291851  0.296668
11  2024-04   92  0.467391  0.647603  0.295206  0.251068
12  2024-05  227  0.361233  0.483347 -0.033305  0.104794
13  2024-06  367  0.264305  0.569702  0.139404  0.127071
14  2024-07  276  0.326087  0.629002  0.258005  0.233333
15  2024-08  411  0.304136  0.683860  0.367720  0.300420
16  2024-09  247  0.372470  0.681101  0.362202  0.280365
17  2024-10  334  0.218563  0.637380  0.274760  0.236341
18  2024-11  349  0.297994  0.583929  0.167857  0.172645
19  2024-12  291  0.305842  0.600679  0.201357  0.154133
20  2025-01  488  0.395492  0.654870  0.309739  0.234636
21  2025-02  408  0.473039  0.695698  0.391397  0.300253
22  2025-03  304  0.138158  0.605462  0.210923  0.220829
23  2025-04  304  0.187500  0.649194  0.298388  0.346829
24  2025-05  113  0.265487  0.693373  0.386747  0.334940
25  2025-06   94  0.180851  0.645913  0.291826  0.291062
26  2025-07   95  0.115789  0.645022  0.290043  0.354978
27  2025-08   63  0.111111  0.548469  0.096939  0.250000
28  2025-09   54  0.055556  0.751634  0.503268  0.529412
29  2025-10   55  0.090909  0.652000  0.304000  0.400000

----------------------------------------------------------------------
TARGET_60 | OBS = 6,731
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2023-01  152  0.184211  0.605127  0.210253  0.223502
1   2023-02  394  0.187817  0.621305  0.242610  0.176858
2   2023-03  117  0.247863  0.539577  0.079154  0.082680
3   2023-05  111  0.108108  0.602694  0.205387  0.255051
4   2023-06  283  0.098940  0.480602 -0.038796  0.165266
5   2023-07  237  0.181435  0.567190  0.134380  0.146608
6   2023-08  229  0.135371  0.666341  0.332682  0.341316
7   2023-09  155  0.206452  0.543064  0.086128  0.133892
8   2024-01  107  0.242991  0.625119  0.250237  0.250712
9   2024-02  115  0.252174  0.607257  0.214515  0.212911
10  2024-03  100  0.230000  0.598250  0.196499  0.232637
11  2024-04   92  0.239130  0.644156  0.288312  0.292208
12  2024-05  227  0.211454  0.515421  0.030843  0.059358
13  2024-06  367  0.125341  0.620513  0.241027  0.193485
14  2024-07  276  0.195652  0.626877  0.253754  0.204705
15  2024-08  411  0.121655  0.690360  0.380720  0.329086
16  2024-09  247  0.198381  0.663987  0.327974  0.269841
17  2024-10  334  0.101796  0.692255  0.384510  0.291569
18  2024-11  349  0.137536  0.610846  0.221692  0.216708
19  2024-12  291  0.151203  0.548307  0.096614  0.119433
20  2025-01  488  0.202869  0.650918  0.301836  0.216198
21  2025-02  408  0.281863  0.682742  0.365484  0.271643
22  2025-03  304  0.052632  0.591688  0.183377  0.326389
23  2025-04  304  0.088816  0.646611  0.293221  0.339885
24  2025-05  113  0.141593  0.761276  0.522552  0.461340
25  2025-06   94  0.074468  0.648604  0.297209  0.367816
26  2025-07   95  0.042105  0.792582  0.585165  0.541209
27  2025-08   63  0.015873  0.822581  0.645161  0.790323
28  2025-09   54  0.018519  0.679245  0.358491  0.660377
29  2025-10   55  0.054545  0.660256  0.320513  0.358974

----------------------------------------------------------------------
TARGET_90 | OBS = 6,731
----------------------------------------------------------------------
      MONTH  OBS  BAD_RATE       AUC      GINI        KS
0   2023-01  152  0.131579  0.645455  0.290909  0.333333
1   2023-02  394  0.121827  0.608652  0.217305  0.165101
2   2023-03  117  0.179487  0.523562  0.047123  0.087798
3   2023-05  111  0.054054  0.686508  0.373016  0.504762
4   2023-06  283  0.060071  0.481424 -0.037152  0.212074
5   2023-07  237  0.147679  0.558911  0.117822  0.131117
6   2023-08  229  0.082969  0.648747  0.297494  0.355138
7   2023-09  155  0.135484  0.489339 -0.021322  0.121180
8   2024-01  107  0.112150  0.589474  0.178947  0.200877
9   2024-02  115  0.139130  0.536301  0.072601  0.109848
10  2024-03  100  0.160000  0.633929  0.267857  0.300595
11  2024-04   92  0.195652  0.666291  0.332583  0.348348
12  2024-05  227  0.140969  0.531651  0.063301  0.090865
13  2024-06  367  0.084469  0.604935  0.209869  0.181932
14  2024-07  276  0.134058  0.643730  0.287459  0.302273
15  2024-08  411  0.072993  0.705337  0.410674  0.299213
16  2024-09  247  0.129555  0.698910  0.397820  0.353924
17  2024-10  334  0.056886  0.729156  0.458312  0.373935
18  2024-11  349  0.094556  0.621260  0.242520  0.251534
19  2024-12  291  0.106529  0.562593  0.125186  0.167618
20  2025-01  488  0.135246  0.695946  0.391893  0.298578
21  2025-02  408  0.220588  0.683159  0.366317  0.264361
22  2025-03  304  0.023026  0.460798 -0.078403  0.275613
23  2025-04  304  0.046053  0.719212  0.438424  0.486700
24  2025-05  113  0.070796  0.815476  0.630952  0.560714
25  2025-06   94  0.021277  0.937500  0.875000  0.902174
26  2025-07   95  0.031579  0.788043  0.576087  0.525362
27  2025-08   63  0.015873  0.822581  0.645161  0.790323
28  2025-10   55  0.036364  0.816038  0.632075  0.698113

==========================================================================================
MODEL: 343
==========================================================================================

----------------------------------------------------------------------
TARGET_30 | OBS = 46,728
----------------------------------------------------------------------
      MONTH   OBS  BAD_RATE       AUC      GINI        KS
0   2024-02   508  0.643701  0.524913  0.049825  0.061196
1   2024-03  1743  0.646586  0.528658  0.057317  0.051575
2   2024-04  5106  0.694477  0.489948 -0.020104  0.034475
3   2024-05  2762  0.679580  0.513298  0.026596  0.056651
4   2024-06  2369  0.685943  0.532289  0.064577  0.047960
5   2024-07  3394  0.734532  0.517698  0.035397  0.027010
6   2024-08  3611  0.703406  0.516769  0.033539  0.030533
7   2024-09  3007  0.686066  0.500896  0.001793  0.017303
8   2024-10  2442  0.685504  0.530194  0.060389  0.054818
9   2024-11  1656  0.663043  0.562452  0.124905  0.095981
10  2024-12   874  0.671625  0.510972  0.021945  0.023791
11  2025-01  2924  0.719904  0.508770  0.017539  0.025913
12  2025-02  7083  0.715516  0.530550  0.061099  0.051089
13  2025-03  7043  0.698566  0.553938  0.107876  0.090641
14  2025-04  1321  0.614686  0.535671  0.071341  0.058944
15  2025-09    85  0.352941  0.631212  0.262424  0.221212
16  2025-10   433  0.457275  0.547980  0.095960  0.078487
17  2025-11   346  0.355491  0.584600  0.169200  0.138321

----------------------------------------------------------------------
TARGET_60 | OBS = 46,728
----------------------------------------------------------------------
      MONTH   OBS  BAD_RATE       AUC      GINI        KS
0   2024-02   508  0.482283  0.507605  0.015209  0.029363
1   2024-03  1743  0.473322  0.513192  0.026384  0.046928
2   2024-04  5106  0.462789  0.513510  0.027021  0.041233
3   2024-05  2762  0.468139  0.505090  0.010180  0.051181
4   2024-06  2369  0.475306  0.528122  0.056244  0.054076
5   2024-07  3394  0.514437  0.545958  0.091916  0.076571
6   2024-08  3611  0.481861  0.527460  0.054919  0.039277
7   2024-09  3007  0.473894  0.520675  0.041350  0.046469
8   2024-10  2442  0.447993  0.539524  0.079047  0.069961
9   2024-11  1656  0.458937  0.532559  0.065118  0.060961
10  2024-12   874  0.456522  0.516568  0.033135  0.041805
11  2025-01  2924  0.502394  0.523164  0.046329  0.045200
12  2025-02  7083  0.503600  0.530888  0.061776  0.053792
13  2025-03  7043  0.514837  0.562723  0.125445  0.105577
14  2025-04  1321  0.428463  0.553439  0.106878  0.093396
15  2025-09    85  0.176471  0.601905  0.203810  0.180952
16  2025-10   433  0.314088  0.491657 -0.016686  0.069098
17  2025-11   346  0.210983  0.560665  0.121331  0.120829

----------------------------------------------------------------------
TARGET_90 | OBS = 46,728
----------------------------------------------------------------------
      MONTH   OBS  BAD_RATE       AUC      GINI        KS
0   2024-02   508  0.385827  0.495192 -0.009615  0.063187
1   2024-03  1743  0.376363  0.498801 -0.002398  0.033049
2   2024-04  5106  0.353506  0.516509  0.033017  0.046059
3   2024-05  2762  0.369298  0.502930  0.005860  0.046900
4   2024-06  2369  0.374842  0.520027  0.040053  0.043777
5   2024-07  3394  0.406305  0.548796  0.097592  0.067880
6   2024-08  3611  0.379119  0.519230  0.038460  0.032419
7   2024-09  3007  0.355171  0.528853  0.057706  0.041141
8   2024-10  2442  0.338247  0.530385  0.060771  0.062030
9   2024-11  1656  0.355072  0.543750  0.087501  0.074543
10  2024-12   874  0.355835  0.501434  0.002867  0.040321
11  2025-01  2924  0.398769  0.519971  0.039941  0.041990
12  2025-02  7083  0.401384  0.532153  0.064306  0.064589
13  2025-03  7043  0.416868  0.557667  0.115335  0.098525
14  2025-04  1321  0.345193  0.555110  0.110220  0.093791
15  2025-09    85  0.117647  0.652667  0.305333  0.333333
16  2025-10   433  0.230947  0.491351 -0.017297  0.041802
17  2025-11   346  0.141618  0.528070  0.056140  0.073937

==========================================================================================
MODEL: 504
==========================================================================================

----------------------------------------------------------------------
TARGET_30 | OBS = 1,118
----------------------------------------------------------------------
     MONTH  OBS  BAD_RATE       AUC      GINI        KS
0  2024-07   84  0.321429  0.669916  0.339831  0.331384
1  2024-08   78  0.282051  0.748782  0.497565  0.461039
2  2024-09   59  0.288136  0.717787  0.435574  0.431373
3  2024-10   69  0.260870  0.583333  0.166667  0.199346
4  2024-11   61  0.377049  0.479405 -0.041190  0.181922
5  2024-12   94  0.542553  0.474236 -0.051528  0.163703
6  2025-01   96  0.520833  0.610000  0.220000  0.230435
7  2025-02  166  0.548193  0.537949  0.075897  0.091868
8  2025-03  211  0.625592  0.584053  0.168105  0.175585
9  2025-04  102  0.490196  0.533269  0.066538  0.139231

----------------------------------------------------------------------
TARGET_60 | OBS = 1,118
----------------------------------------------------------------------
     MONTH  OBS  BAD_RATE       AUC      GINI        KS
0  2024-07   84  0.178571  0.562802  0.125604  0.211594
1  2024-08   78  0.153846  0.773359  0.546717  0.424242
2  2024-09   59  0.220339  0.739130  0.478261  0.401338
3  2024-10   69  0.115942  0.526639  0.053279  0.194672
4  2024-11   61  0.229508  0.506839  0.013678  0.142857
5  2024-12   94  0.340426  0.532510  0.065020  0.112903
6  2025-01   96  0.385417  0.614292  0.228585  0.202016
7  2025-02  166  0.391566  0.573877  0.147753  0.129627
8  2025-03  211  0.530806  0.595960  0.191919  0.213925
9  2025-04  102  0.411765  0.502976  0.005952  0.119048

----------------------------------------------------------------------
TARGET_90 | OBS = 1,116
----------------------------------------------------------------------
     MONTH  OBS  BAD_RATE       AUC      GINI        KS
0  2024-07   84  0.130952  0.622665  0.245330  0.297634
1  2024-08   78  0.128205  0.820588  0.641176  0.473529
2  2024-09   59  0.169492  0.675510  0.351020  0.367347
3  2024-10   69  0.057971  0.598077  0.196154  0.423077
4  2024-11   61  0.213115  0.500000  0.000000  0.153846
5  2024-12   94  0.255319  0.526190  0.052381  0.132143
6  2025-01   96  0.343750  0.567581  0.135161  0.171717
7  2025-02  166  0.319277  0.588996  0.177993  0.157121
8  2025-03  211  0.445498  0.575696  0.151391  0.185125
9  2025-04  102  0.333333  0.487673 -0.024654  0.132353

==========================================================================================
MODEL: 727
==========================================================================================

----------------------------------------------------------------------
TARGET_30 | OBS = 18,827
----------------------------------------------------------------------
      MONTH   OBS  BAD_RATE       AUC      GINI        KS
0   2025-04  1462  0.112859  0.711979  0.423957  0.351898
1   2025-05  2372  0.115514  0.725334  0.450667  0.327813
2   2025-06  2326  0.097163  0.671602  0.343205  0.270796
3   2025-07  2388  0.074958  0.743147  0.486294  0.413436
4   2025-08  2363  0.066864  0.753546  0.507093  0.418824
5   2025-09  2113  0.059158  0.755757  0.511513  0.393521
6   2025-10  2394  0.049290  0.751044  0.502089  0.413653
7   2025-11  1733  0.037507  0.728662  0.457323  0.376536
8   2025-12   794  0.050378  0.764871  0.529741  0.444363
9   2026-01   239  0.012552  0.781073  0.562147  0.665254
10  2026-02   218  0.022936  0.530516  0.061033  0.238498
11  2026-03   171  0.005848  0.458824 -0.082353  0.535294
12  2026-04   164  0.018293  0.919255  0.838509  0.919255

----------------------------------------------------------------------
TARGET_60 | OBS = 18,663
----------------------------------------------------------------------
     MONTH   OBS  BAD_RATE       AUC      GINI        KS
0  2025-04  1462  0.040356  0.747629  0.495258  0.400232

In [2]:
# Model 727
# Juda kuchli model, yuqori lift va stabil signal
# TARGET 30: AUC ~0.71–0.78 → yuqori va stabil
# TARGET 60: AUC ~0.69–0.77 → juda barqaror
# TARGET 90: AUC ~0.69–0.78 → eng stabil segment
# Kuzatuv:
# 2026 boshida TARGET 30 da keskin spike (AUC 0.91) va volatility kuzatildi
# OBS kichik oylar natijani distort qilgan bo‘lishi mumkin
# Xulosa:
# Model kuchli, lekin recent periodda small-sample instability signali bor
# 
# Model 504
# Umumiy baho: Yaxshi, lekin juda volatile model
# TARGET 30: AUC 0.47–0.74 → kuchli tebranish
# TARGET 60: AUC 0.50–0.77 → unstable
# TARGET 90: AUC 0.50–0.82 → ba’zan juda kuchli spike
# Kuzatuv:
# Oylik performance “wave pattern” ko‘rsatadi
# Ba’zi davrlarda keskin drop (0.47 atrofida)
# Xulosa:
# Modelda drift + instability mavjud, lekin signal hali saqlangan
# 
# Model 184
# Umumiy baho: O‘rtacha, seasonal drift bor
# TARGET 30: AUC 0.54–0.69 → o‘rtacha
# TARGET 60: AUC 0.50–0.69 → stabilroq
# TARGET 90: AUC 0.49–0.66 → nisbatan yaxshi
# Kuzatuv:
# Ba’zi oylarda drop (2024-05, 2024-12)
# Ba’zi oylarda recovery (2024-08, 2025-09)
# Xulosa:
# Model ishlaydi, lekin seasonality va drift ta’siri bor
# 
# Model 122
# Umumiy baho: Zaif va beqaror model
# TARGET 30: AUC 0.38–0.73 → inconsistent
# TARGET 60: AUC 0.40–0.71 → unstable
# TARGET 90: AUC 0.35–0.65 → weak signal
# Kuzatuv:
# Ba’zi oylarda yaxshi, lekin tez buziladi
# Negative / near-random periods mavjud
# Xulosa:
# Modelda barqaror predictive power yo‘q
# 
# Model 343
# Umumiy baho: Juda kuchsiz model (near-random)
# TARGET 30: AUC ~0.49–0.55
# TARGET 60: AUC ~0.49–0.55
# TARGET 90: AUC ~0.49–0.55
# Kuzatuv:
# KS juda past
# AUC deyarli random (0.5 atrofida)
# Hech qanday stabil signal yo‘q
# 
# Xulosa:
# Model predictive value bermaydi

In [18]:
def stability_score(df_time):

    df_time = df_time.copy()

    # =========================
    # SAFETY CHECK
    # =========================
    if len(df_time) < 3:
        return {
            'GINI_VOLATILITY': np.nan,
            'KS_VOLATILITY': np.nan,
            'GINI_CV': np.nan,
            'KS_CV': np.nan
        }

    # =========================
    # STATS
    # =========================
    gini_mean = df_time['GINI'].mean()
    ks_mean = df_time['KS'].mean()

    gini_std = df_time['GINI'].std()
    ks_std = df_time['KS'].std()

    return {
        'GINI_VOLATILITY': gini_std,
        'KS_VOLATILITY': ks_std,
        'GINI_CV': gini_std / (abs(gini_mean) + 1e-6),
        'KS_CV': ks_std / (abs(ks_mean) + 1e-6)
    }
time_summary = []

for key, df_time in all_time_metrics.items():

    scoring_id, target = key

    if len(df_time) < 2:
        continue

    stats = stability_score(df_time)

    time_summary.append({
        'SCORING_ID': scoring_id,
        'TARGET': target,

        # =========================
        # LEVEL
        # =========================
        'AVG_GINI': df_time['GINI'].mean(),
        'STD_GINI': df_time['GINI'].std(),

        'AVG_KS': df_time['KS'].mean(),
        'STD_KS': df_time['KS'].std(),

        # =========================
        # STABILITY (NEW)
        # =========================
        'GINI_VOLATILITY': stats['GINI_VOLATILITY'],
        'KS_VOLATILITY': stats['KS_VOLATILITY'],
        'GINI_CV': stats['GINI_CV'],
        'KS_CV': stats['KS_CV'],

        # =========================
        # EXTRA INSIGHT (OPTIONAL BUT USEFUL)
        # =========================
        'GINI_MIN': df_time['GINI'].min(),
        'GINI_MAX': df_time['GINI'].max(),
        'KS_MIN': df_time['KS'].min(),
        'KS_MAX': df_time['KS'].max()
    })

time_summary_df = pd.DataFrame(time_summary)
time_summary_df

,SCORING_ID,TARGET,AVG_GINI,STD_GINI,AVG_KS,STD_KS,GINI_VOLATILITY,KS_VOLATILITY,GINI_CV,KS_CV,GINI_MIN,GINI_MAX,KS_MIN,KS_MAX
0,42,TARGET_30,0.187489,0.149884,0.225984,0.091971,0.149884,0.091971,0.799426,0.406977,-0.054245,0.403759,0.102460,0.407519
1,42,TARGET_60,0.324916,0.266342,0.411121,0.213827,0.266342,0.213827,0.819722,0.520107,-0.057255,0.850704,0.140857,0.859155
2,42,TARGET_90,0.243062,0.359935,0.460169,0.206549,0.359935,0.206549,1.480827,0.448853,-0.531447,0.844749,0.194602,0.876712
3,122,TARGET_30,0.095105,0.175478,0.234902,0.099286,0.175478,0.099286,1.845074,0.422670,-0.235192,0.464387,0.152381,0.457265
4,122,TARGET_60,0.123722,0.204031,0.295567,0.118536,0.204031,0.118536,1.649095,0.401044,-0.193878,0.431034,0.172414,0.490566
5,122,TARGET_90,0.108456,0.210288,0.309396,0.120981,0.210288,0.120981,1.938906,0.391021,-0.282051,0.467742,0.173729,0.486175
6,184,TARGET_30,0.230271,0.128947,0.236068,0.104741,0.128947,0.104741,0.559976,0.443689,-0.033305,0.503268,0.087651,0.529412
7,184,TARGET_60,0.267050,0.150623,0.284399,0.159844,0.150623,0.159844,0.564023,0.562038,-0.038796,0.645161,0.059358,0.790323
8,184,TARGET_90,0.303787,0.228378,0.334255,0.206568,0.228378,0.206568,0.751769,0.617992,-0.078403,0.875000,0.087798,0.902174
9,343,TARGET_30,0.068979,0.066415,0.064772,0.049425,0.066415,0.049425,0.962818,0.763054,-0.020104,0.262424,0.017303,0.221212
10,343,TARGET_60,0.063856,0.051990,0.068148,0.037228,0.051990,0.037228,0.814156,0.546267,-0.016686,0.203810,0.029363,0.180952
11,343,TARGET_90,0.060322,0.073116,0.072182,0.068033,0.073116,0.068033,1.212083,0.942506,-0.017297,0.305333,0.032419,0.333333
12,504,TARGET_30,0.187746,0.188347,0.240589,0.125173,0.188347,0.125173,1.003196,0.520276,-0.051528,0.497565,0.091868,0.461039
13,504,TARGET_60,0.185677,0.187633,0.215222,0.111167,0.187633,0.111167,1.010529,0.516518,0.005952,0.546717,0.112903,0.424242
14,504,TARGET_90,0.192595,0.193872,0.249389,0.129913,0.193872,0.129913,1.006624,0.520923,-0.024654,0.641176,0.132143,0.473529
15,727,TARGET_30,0.430094,0.227785,0.443780,0.179573,0.227785,0.179573,0.529615,0.404642,-0.082353,0.838509,0.238498,0.919255
16,727,TARGET_60,0.473528,0.059421,0.415920,0.060269,0.059421,0.060269,0.125487,0.144906,0.384006,0.543465,0.329843,0.485435
17,727,TARGET_90,0.441127,0.140868,0.425652,0.093794,0.140868,0.093794,0.319336,0.220352,0.119304,0.576349,0.293038,0.581505

In [19]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from scipy.stats import ks_2samp

final_summary = []

for scoring_id, df_model in df.groupby('SCORING_ID'):

    df_model = df_model.copy()
    df_model['APPLICATION_DATE'] = pd.to_datetime(df_model['APPLICATION_DATE'])

    for target, maturity_days in targets.items():

        cutoff_date = max_date - pd.Timedelta(days=maturity_days)

        tmp_model = df_model[df_model['APPLICATION_DATE'] <= cutoff_date]

        if len(tmp_model) < 100 or tmp_model[target].nunique() < 2:
            continue

        # =========================
        # AUC / GINI
        # =========================
        auc = roc_auc_score(tmp_model[target], -tmp_model['SCORE_BALL'])
        gini = 2 * auc - 1

        # =========================
        # KS (CONSISTENT SIGN)
        # =========================
        ks = ks_2samp(
            -tmp_model.loc[tmp_model[target] == 0, 'SCORE_BALL'],
            -tmp_model.loc[tmp_model[target] == 1, 'SCORE_BALL']
        ).statistic

        # =========================
        # PSI (SAFE + NO OVERLAP BIAS FIX)
        # =========================
        dates = np.sort(tmp_model['APPLICATION_DATE'].unique())

        if len(dates) > 5:
            split_date = dates[int(len(dates) * 0.7)]

            dev_df = tmp_model[tmp_model['APPLICATION_DATE'] <= split_date]
            oot_df = tmp_model[tmp_model['APPLICATION_DATE'] > split_date]

            psi = calculate_psi(
                dev_df['SCORE_BALL'].dropna(),
                oot_df['SCORE_BALL'].dropna()
            ) if len(dev_df) > 50 and len(oot_df) > 50 else np.nan
        else:
            psi = np.nan

        # =========================
        # LIFT (FIXED DECILE SAFETY)
        # =========================
        tmp = tmp_model[[target, 'SCORE_BALL']].dropna().copy()

        tmp['DECILE'] = pd.qcut(
            tmp['SCORE_BALL'],
            q=10,
            labels=False,
            duplicates='drop'
        ) + 1

        lift_table = (
            tmp.groupby('DECILE')[target].mean().sort_index()
        )

        overall_br = tmp[target].mean()

        # FIX: explicit worst decile assumption
        top_lift = (lift_table.iloc[0] / overall_br) if overall_br > 0 else np.nan

        # =========================
        # STORE
        # =========================
        final_summary.append({
            'SCORING_ID': scoring_id,
            'TARGET': target,

            'OBS': len(tmp_model),

            # performance
            'AUC': auc,
            'GINI': gini,
            'KS': ks,

            # stability
            'PSI': psi,

            # ranking power
            'TOP_LIFT': top_lift,

        })

def risk_flag(row):

    # =========================
    # HARD FAIL CONDITIONS
    # =========================
    if (row['GINI'] < 0.2) or (row['KS'] < 0.1):
        return 'BAD'

    # =========================
    # WARNING CONDITIONS (MORE REALISTIC)
    # =========================
    if (
        (row['PSI'] > 0.25) 
    ):
        return 'WARNING'

    return 'GOOD'


final_df = pd.DataFrame(final_summary)
final_df['STATUS'] = final_df.apply(risk_flag, axis=1)

final_df

,SCORING_ID,TARGET,OBS,AUC,GINI,KS,PSI,TOP_LIFT,STATUS
0,42,TARGET_30,2643,0.545942,0.091884,0.077590,4.624665,1.410519,BAD
1,42,TARGET_60,2643,0.565131,0.130261,0.108563,4.624665,1.646034,BAD
2,42,TARGET_90,2643,0.541962,0.083924,0.078253,4.624665,1.650042,BAD
3,122,TARGET_30,1272,0.533602,0.067205,0.122124,0.458152,0.845502,BAD
4,122,TARGET_60,1272,0.539769,0.079538,0.159923,0.458152,0.764686,BAD
5,122,TARGET_90,1271,0.538424,0.076849,0.148820,0.472882,0.516387,BAD
6,184,TARGET_30,6731,0.567923,0.135846,0.117062,0.688074,1.274479,BAD
7,184,TARGET_60,6731,0.563953,0.127907,0.102537,0.688074,1.294397,BAD
8,184,TARGET_90,6731,0.563919,0.127838,0.096852,0.688074,1.302399,BAD
9,343,TARGET_30,46728,0.516976,0.033951,0.032126,2.402779,1.019762,BAD
10,343,TARGET_60,46728,0.513368,0.026737,0.026329,2.402779,1.030530,BAD
11,343,TARGET_90,46728,0.508259,0.016518,0.022254,2.402779,1.015701,BAD
12,504,TARGET_30,1118,0.604509,0.209018,0.156184,1.481949,1.400046,WARNING
13,504,TARGET_60,1118,0.621132,0.242264,0.179544,1.481949,1.578233,WARNING
14,504,TARGET_90,1116,0.615075,0.230149,0.165185,1.557819,1.488413,WARNING
15,727,TARGET_30,18827,0.720185,0.440370,0.334232,0.109937,2.462483,GOOD
16,727,TARGET_60,18663,0.730260,0.460521,0.368599,0.019976,2.832224,GOOD
17,727,TARGET_90,18505,0.728304,0.456607,0.373838,0.006917,2.614504,GOOD

In [ ]:
# MODEL 42 bo‘yicha natijalar shuni ko‘rsatadiki, modelning discriminative kuchi past (GINI 0.08–0.13, KS 0.07–0.11). 
# TOP LIFT 1.4–1.65 atrofida bo‘lib, faqat minimal uplift beradi. PSI juda yuqori (~4.62) bo‘lgani uchun vaqt bo‘yicha kuchli drift mavjud. 
# Umuman olganda, model barqaror emas va signal kuchsiz, shuning uchun production uchun xavfli (BAD).
# 
# MODEL 122 da ham xuddi shunga o‘xshash holat kuzatiladi: GINI juda past (0.06–0.08), KS past (0.12–0.16), 
# TOP LIFT esa 1 dan past darajaga tushib ketgan. PSI ~0.46 bo‘lib, o‘rtacha drift mavjud. 
# Model deyarli random behaviorga yaqin va kredit riskni ajratish qobiliyati juda zaif, shu sababli model ishonchsiz (BAD).
# 
# MODEL 184 da biroz yaxshiroq signal mavjud (GINI 0.12–0.13, KS 0.09–0.11), TOP LIFT ~1.27–1.30 atrofida. 
# Biroq PSI ~0.68 bo‘lib, sezilarli drift mavjud. Bu modelda signal bor, lekin vaqt bo‘yicha barqaror emas, shuning uchun o‘rtacha sifatli, 
# lekin riskli model hisoblanadi (BAD).
# 
# MODEL 343 eng zaif model hisoblanadi. GINI juda past (0.01–0.03), KS ham juda past (0.02–0.03), 
# TOP LIFT esa ~1 atrofida, ya’ni deyarli hech qanday ranking kuchi yo‘q. PSI ~2.40 bo‘lib, katta drift ham mavjud. 
# Bu model amalda predictive value bermaydi va random modelga yaqin (BAD).
# 
# MODEL 504 o‘rtacha darajadagi model hisoblanadi. GINI 0.21–0.24, KS 0.15–0.18 bo‘lib, signal mavjudligini ko‘rsatadi. 
# TOP LIFT 1.4–1.57 atrofida bo‘lib, yaxshi uplift beradi. Biroq PSI ~1.48 bo‘lgani uchun drift mavjud. 
# Model ishlatilishi mumkin, lekin doimiy monitoring talab etiladi (WARNING).
# 
# MODEL 727 eng yaxshi model hisoblanadi. GINI yuqori (0.44–0.46), KS 0.33–0.37, TOP LIFT esa 2.4–2.8 atrofida bo‘lib juda kuchli ranking power beradi. 
# PSI esa juda past (0.006–0.11), ya’ni model juda stabil. Bu model ham signal, ham stability bo‘yicha eng yaxshi natija ko‘rsatgan va 
# production uchun to‘liq tayyor (GOOD).